vaccine-feed-ingest/run.py

Pull out the update made by @rajbot  into separate PR so it can be merged separately

Dry get_site_dirs code

---

vaccine_feed_ingest/run.py

Use find_executable to check if the stage exists

Fix available sites command

---

vaccine_feed_ingest/run.py

Sometimes it wouldn't return the sites for states, however always yielding fixes it.

Fix get_site_dirs to always yield

---

README.md
vaccine_feed_ingest/runners/_template/README.md
vaccine_feed_ingest/runners/_template/fetch.sh
vaccine_feed_ingest/runners/_template/normalize.sh
vaccine_feed_ingest/runners/_template/parse.sh

Add instructions to readme about how to contribute a scraper

FYI Document how to contribute a scraper

---

README.md

Minor improvements to readme

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/ingestors/arcgis.py
vaccine_feed_ingest/runners/al/arcgis/fetch.py

Example ArcGIS fetcher:
Run with:
```
mkdir out
poetry run vaccine-feed-ingest fetch --state=al --output-dir=out
```
ArcGIS json results will be copied to `out/`.

Add Alabama fetcher

---

vaccine_feed_ingest/runners/md/arcgis/fetch.py

Fetch Maryland's information using the [ArcGIS runner](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/arcgis-runner).

chore: fetch MD ArcGIS

---

vaccine_feed_ingest/ingestors/arcgis.py

In the ArcGIS ingestor, we poll the service item to enumerate available
layers.
Leverage this information to help developers sanity-check their code:
* If a layer is requested which does not exist, log a warning.
* If a layer is available but is not requested, inform the developer so
they can consider including it.
Sample logging:
```sh
$: poetry run vaccine-feed-ingest fetch md/arcgis
Starting MD scraper with output_dir='/var/folders/cm/hywwvgwn70n79jzc6676jrbc0000gn/T/tmp_noqfwey_fetch_arcgis/output'
04/15/2021 01:17:47 WARNING:arcgis:d677f143334648a1a40b84d94df8e134 - requested layers which do not exist - {'Fake typo layer'}
04/15/2021 01:17:47 INFO:arcgis:d677f143334648a1a40b84d94df8e134 - additional layers available but not selected - {'Hospital Vaccination Sites', 'Pharmacy …
```

feat: log unexpected layer selection

---

vaccine_feed_ingest/runners/ak/arcgis/fetch.yml

Fetch Alaska's ArcGIS data using the new pattern established in #26.
This file contains ~150 locations. A sample location is as follows:
```json
{
"attributes": {
"address": "3521 Mountain View Dr.",
"city": "Anchorage",
"cost_other": null,
"datesubmited": 1611954000000,
"flu_acceptsInsurance": "yes_please_contact_your_insuran",
"flu_cost": "no_cost",
"flu_vaccinations": "Janssen",
"flu_walkins": "no_please_make_an_appointment",
"globalid": "f8279fb5-f72e-46d1-822c-743ab429d0a2",
"needs_review": "approved",
"objectid": 126,
"phone": "<REDACTED>",
"publicEmail": null,
"publicNotes": null,
"publicWebsite": "https://mvucak.com/covid-vaccinations",
"vaccinationSite": "Mountain View Urgent Care ",
"zipcode": "99508"
},
"geometry": {
"spatialReference": {
"latestWkid": 4326,
"wkid": 4326
}, …
```

feat: fetch Alaska arcgis

---

vaccine_feed_ingest/runners/az/arcgis/fetch.yml
vaccine_feed_ingest/runners/in/arcgis/fetch.yml
vaccine_feed_ingest/runners/mo/arcgis/fetch.yml
vaccine_feed_ingest/runners/mt/arcgis/fetch.yml
vaccine_feed_ingest/runners/pa/arcgis/fetch.yml
vaccine_feed_ingest/runners/ri/arcgis/fetch.yml
vaccine_feed_ingest/runners/sc/arcgis/fetch.yml
vaccine_feed_ingest/runners/tx/arcgis/fetch.yml

Fetch ArcGIS files for several more states.

chore: fetch AZ, IN, MO, MT, PA, RI, SC, TX ArcGIS

---

vaccine_feed_ingest/run.py

Currently runners are namespaced: `<state_or_us>/<site>/<stage>`, but our output directories are simply `<site>/<stage>` and our temporary working directories are simply `<stage>_<site>`. This means that site names must be globally unique to ensure that files end up in isolated directories.
As a result of this, non-unique site names (like `arcgis`) were being repeatedly parsed and normalized because the temp directories were shared.
Update `run.py` to:
* name temporary working directories `<stage>_<site_or_us>_<site>`
* name output directories `<state_or_us>/<site>/<stage>`

feat!: namespace output and temp dirs

---

README.md
poetry.lock
pyproject.toml

1. Added GCS dependancies by adding `pathy[gcs]`
2. Documented how to test the dependancies locally

Add GCS dependancies and document GCS steps

---

vaccine_feed_ingest/runners/ny/nyc_arcgis/fetch.yml

Fixes #53.
Fetch data from NYC's ArcGIS featureserver, found at https://services1.arcgis.com/oOUgp466Coyjcu6V/arcgis/rest/services/VaccineFinder_Production_View/FeatureServer.
This data is contains about 600 well-structured locations. Here's a sample of one:
```json
{
"attributes": {
"ADA_Compliant": "No",
"AdditionalInfo": "",
"Address": "200 Central Park West",
"Address2": "",
"AgesServed": "",
"AgesServed2": "",
"AgesServed3": "",
"AgesServed_Over18": "",
"AgesServed_Under18": "",
"AppointmentAvailability": "Available",
"AvailabilityCount": null,
"AvailabilityETLLastModified": 1619157375161,
"AvailabilitySource": "NYC DoITT Salesforce",
"AvailabilitySourceLastModified": null,
"Borough": "Manhattan",
"ClosingHour_Friday": 1800,
"ClosingHour_Monday": 1800,
"ClosingHour_Saturday": 1800, …
```

fetch nyc_arcgis

---

vaccine_feed_ingest/cli.py
vaccine_feed_ingest/runners/ca/sf_gov/normalize.py
vaccine_feed_ingest/stages/load.py
vaccine_feed_ingest/utils/match.py
vaccine_feed_ingest/utils/normalize.py
vaccine_feed_ingest/vial.py

Implemnt basic matching logic using concordances and addresses.

---

vaccine_feed_ingest/runners/_shared/parse.py
vaccine_feed_ingest/runners/ak/arcgis/parse.yml
vaccine_feed_ingest/runners/al/arcgis/parse.yml
vaccine_feed_ingest/runners/az/arcgis/parse.yml
vaccine_feed_ingest/runners/in/arcgis/parse.yml
vaccine_feed_ingest/runners/md/arcgis/parse.yml
vaccine_feed_ingest/runners/mo/arcgis/parse.yml
vaccine_feed_ingest/runners/mt/arcgis/parse.yml
vaccine_feed_ingest/runners/pa/arcgis/parse.yml
vaccine_feed_ingest/runners/ri/arcgis/parse.yml
vaccine_feed_ingest/runners/sc/arcgis/parse.yml
vaccine_feed_ingest/runners/tx/arcgis/parse.yml

- refactor: parser.yml must specify a parser to run
- refactor: split code into functions
- chore: general parser for list of json objects

chore: general parser for list of json objects

---

vaccine_feed_ingest/stages/load.py
vaccine_feed_ingest/vial.py

1. Use `existing` when matching
2. Don't pass fields with `None`

FYI Change import to VIAL code to be the same as the VIAL api

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/ma/fetch.sh
vaccine_feed_ingest/runners/ma/parse.py

Resolves #69 and #70.
This PR handles the fetch + parse steps for MA. 
Since we're not using the availability data at the moment, I decided to use their xlsx source as it's easier to get started with - ie. no pagination required, dates are better formatted. 
See slack thread: https://vaccine-feeds.slack.com/archives/G01PX9KH34H/p1619204038086500?thread_ts=1619203431.085900&cid=G01PX9KH34H
Sample data:
```
{"name": "Haverhill: Walgreens (River St.)", "address": "800 River St., Haverhill, MA 01832"}
{"name": "Haverhill: Walgreens (South Main St.)", "address": "68 South Main St, Haverhill, MA 01835"}
{"name": "Hingham: CVS (Lincoln St.)", "address": "405 Lincoln St, Hingham, MA 02043"}
{"name": "Hingham: CVS (South Street)", "address": "86 South Street, Hingham, MA 02043"}
```

Add Fetch + Parse steps for Mass.

---

vaccine_feed_ingest/runners/ct/fetch.sh
vaccine_feed_ingest/runners/ct/normalize.py
vaccine_feed_ingest/runners/ct/parse.py

Resolves #63.
Resolves #64.
Resolves #65.
Fetches data from CT's API and parses/normalizes to ndjson.
Data:
```{"id": "ct_gov:605a3745494866ed91e08054", "name": "Community Health Center (Middletown)", "address": {"street1": "675 Main Street", "street2": "", "city": "Middletown", "state": "CT", "zip": "06457"}, "location": {"latitude": 41.56506, "longitude": -72.65283}, "contact": [{"contact_type": "booking", "phone": "", "website": "https://portal.ct.gov/Coronavirus/COVID-19-Vaccinations---VAMS-Support"}], "availability": {"appointments": false}, "access": {"drive": false}, "inventory": [{"vaccine": "Moderna"}], "links": [{"authority": "ct_gov", "id": "605a3745494866ed91e08054"}, {"authority": "ct_gov:network_id", "id": "606f5703c12ac9ccdc82429e"}], "parent_organization": {"name": …
```

Fetch/Parse/Normalize CT data

---

vaccine_feed_ingest/runners/ny/am_i_eligible_covid19vaccine_gov/fetch.sh

add fetcher for ny am-i-eligible

---

vaccine_feed_ingest/runners/ny/am_i_eligible_covid19vaccine_gov/parse.py

add ny am-i-eligible parser

---

vaccine_feed_ingest/runners/in/arcgis/fetch.yml
vaccine_feed_ingest/runners/mo/arcgis/fetch.yml

fix: swap in/arcgis and mo/arcgis to correct places

---

vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/parse.yml

Resolves #120 
FYI - @MoralCode

chore: use shared parser for us/giscorps_vaccine_providers

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/ny/am_i_eligible_covid19vaccine_gov/normalize.py
vaccine_feed_ingest/runners/ny/am_i_eligible_covid19vaccine_gov/parse.py

also updates the parser to insert the feed-level `lastUpdated` field into each site.
this should resolve #68.

add normalizer for am_i_eligible_covid19vaccine_gov

---

vaccine_feed_ingest/runners/wi/arcgis_map/parse.yml

add parse.yml for wi arcgis_map

---

vaccine_feed_ingest/runners/tn/arcgis/parse.yml

Add TN parser.

---

vaccine_feed_ingest/cli.py
vaccine_feed_ingest/stages/load.py
vaccine_feed_ingest/vial.py

This should hopefully speed up matching by a lot

Create an index to use for finding match candidates

---

vaccine_feed_ingest/utils/normalize.py

Add CVS regex.

---

vaccine_feed_ingest/runners/me/maine_gov/fetch.py

Fetches a simple HTML page.
Resolves #127.

Add Maine government fetcher.

---

vaccine_feed_ingest/runners/nc/myspot_gov/fetch.py

The _fetch.py_ script uses Selenium to collect data from the NC official website, by querying per NC zip code. The zip codes are collected through the requests library via a third party website. The script takes about 4 minutes to run on my personal computer and produces an html file for each zip code.
Solves issue #87

Added fetch for nc data

---

vaccine_feed_ingest/runners/pa/arcgis/normalize.py

Add normalizer for PA

---

vaccine_feed_ingest/runners/nc/myspot_gov/parse.py

Closes https://github.com/CAVaccineInventory/vaccine-feed-ingest/issues/89.

Add nc/myspot_gov/parse.py

---

vaccine_feed_ingest/utils/normalize.py

Resolves #165 .
This feels icky in that doing the str(int(...)) is repetitive, but it's easy and refactoring to just do it once is probably not worth it.

Remove leading zeros from pharmacy branch IDs.

---

vaccine_feed_ingest/cli.py
vaccine_feed_ingest/stages/load.py
vaccine_feed_ingest/utils/misc.py
vaccine_feed_ingest/vial.py

1. Download all existing locations when starting load.
2. Match source to existing, and load them to source locations
3. Refresh existing locations with any locations that were added as new.

Refresh existing locations index only with newly created locations

---

vaccine_feed_ingest/runners/ca/metrolink/fetch.py

Fetch Metrolink site list.

---

vaccine_feed_ingest/runners/sc/arcgis/normalize.py

Fixes #50  
Example output (had to rename to.txt to get GH to upload): 
[bbd8924909264baaa1a5a1564b393063_0.parsed.normalized.txt](https://github.com/CAVaccineInventory/vaccine-feed-ingest/files/6370950/bbd8924909264baaa1a5a1564b393063_0.parsed.normalized.txt)

Create SC normalizer

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/me/maine_gov/parse.py

Parse Maine government vaccination site list.

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/ga/dph/fetch.sh
vaccine_feed_ingest/runners/ga/dph/parse.py

I've tried keeping the HTML parsing code pretty flexible to keep most of the actual logic in the normalization stage - I guess that'll somewhat flow into each other as we start processing more HTML.

Fetch & parse GA DPH site

---

vaccine_feed_ingest/runners/il/sfsites/README.md
vaccine_feed_ingest/runners/il/sfsites/fetch.py

Add IL sfsites fetcher

---

vaccine_feed_ingest/runners/il/juvare/parse.yml

|-|
| Resolves #194 |
State: il |
Site: juvare |
```json
{"organizer": "IL-IDPH", "slug": "285fe792-fcd0-4ca1-9471-dd92752c84b6", "name": "03/30 to 04/30 - IDHS - Mabley Developmental Center Vaccination POD", "location": "1120 Washington Avenue Dixon, IL 61201", "dateFrom": "3/30/2021, 9:00 AM", "dateTo": "4/30/2021, 3:30 PM", "lat": 41.861388, "lon": -89.479465, "search": "03/30 to 04/30 - idhs - mabley developmental center vaccination pod 1120 washington avenue dixon, il 61201 3/30/2021, 9:00 am 4/30/2021, 3:30 pm"}
{"organizer": "IL-IDPH", "slug": "415331f6-0a4e-423a-b797-3c3aa99bb079", "name": "03/31 to 05/19 - IDHS - Choate Developmental Center Vaccination", "location": "1000 N. Main, Anna, IL 62906", "dateFrom": "3/31/2021, 10:00 AM", "dateTo": "5/19/2021, 7:00 PM", …
```

Parse Juvare for IL

---

vaccine_feed_ingest/stages/load.py

Fix broken import after moving to relative imports

---

vaccine_feed_ingest/runners/il/sfsites/parse.yml

|-|
| Resolves #195 |
State: il |
Site: sfsites |
uses parse.yml
```json
{"Id": "a05t00000096y7sAAA", "Geolocation__Latitude__s": 42.37019, "Geolocation__Longitude__s": -88.83004, "Testing_Center__c": "4-29 - Boone County - Fire District 3 - First Dose", "Website__c": "https://covidvaccination.dph.illinois.gov/", "Postal_Code__c": "61065", "Street__c": "305 West Grove St", "City__c": "Poplar Grove", "Location_Type__c": "Public health provider - public health clinic", "County__c": "Boone"}
{"Id": "a05t00000096y58AAA", "Geolocation__Latitude__s": 39.9338798522949, "Geolocation__Longitude__s": -91.4105606079102, "Testing_Center__c": "ADAMS COUNTY HEALTH DEPARTMENT", "Website__c": "https://www.co.adams.il.us/government/departments/health-department/covid-19-vaccination-informat …
```

Parse il sfsites

---

vaccine_feed_ingest/runners/al/jefferson/fetch.py

|-|
| Resolves #183 |
State: AL |
Site: jefferson |
Run to test
```
poetry run vaccine-feed-ingest fetch al/jefferson
```
N/A. Downloads a PDF.

Add al/jefferson/fetch.py

---

vaccine_feed_ingest/runners/in/arcgis/normalize.py

I copied from the sample AK normalize script and adjusted for the IN input, also see #111. Added now because I'm going to sleep soon.
Resolves #57

Add normalize script for IN arcgis data

---

vaccine_feed_ingest/runners/ga/dph/fetch.py
vaccine_feed_ingest/runners/ga/dph/parse.py

|-|
| Resolves #181 |
State: GA |
Site: DPH |
The first 2 commits here should be ignored because this branch starts where https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/228 leaves off. When that get's merged I'll rebase this on main to clear them out.
```json
{"Location Name": "1st Care Management", "County": "Fulton", "Address": "1120 Hope Rd\nSuite 210\nSandy Springs, GA 30350", "address-parts": {"address-line1": "1120 Hope Rd", "address-line2": "Suite 210", "locality": "Sandy Springs", "administrative-area": "GA", "postal-code": "30350", "country": ""}, "phone-numbers": [], "contact-links": [{"href": "https://1stcaremanagement.com/", "label": "COVID-19 Vaccine Appointments"}], "node-id": "node/42871", "last-updated": "1611102629"}
{"Location Name": …
```

Parse (more) DPH for GA

---

vaccine_feed_ingest/runners/tn/vaccinate_gov/fetch.py

|-|
| Resolves #247 |
State: TN |
Site: vaccine_gov |
There's nothing on the starting page when we first get there so we need to submit a search request that returns all the data, fortunately the search results come back as JSON.
<details>
<summary>raw data snippet</summary>
```json
[
{
"Description": "870 Fairgrounds Rd\r\nAshland City, Tennessee 37015 \u003cbr\u003ePhone No: 866-442-5301 \u003cbr\u003e ",
"Distance": 16.3,
"Id": "0048c3cd-cd76-eb11-a812-001dd801407a",
"Latitude": 36.26931,
"Location": "36.26931,-87.04256",
"Longitude": -87.04256,
"PushpinImageHeight": 39,
"PushpinImageUrl": "",
"PushpinImageWidth": 32,
"Title": "Cheatham County Second Dose Moderna POD",
"Url": ""
},
{
"Description": "870 Fairgrounds Rd\r\nAshland City, Tennessee 37015 \u003cbr\u003ePhone …
```

Fetch vaccine_gov fetch for TN

---

vaccine_feed_ingest/runners/tn/vaccinate_gov/parse.py

|-|
| Resolves #248 |
State: TN |
Site: vaccinate_gov |
```json
{"id": "0048c3cd-cd76-eb11-a812-001dd801407a", "title": "Cheatham County Second Dose Moderna POD", "lat": 36.26931, "long": -87.04256, "address": {"lines": ["870 Fairgrounds Rd"], "city": "Ashland City", "state": "TN", "zip": "37015"}, "phone": "866-442-5301"}
{"id": "9242ebfd-cd76-eb11-a812-001dd801e91f", "title": "Cheatham County First Dose Vaccination POD", "lat": 36.26931, "long": -87.04256, "address": {"lines": ["870 Fairgrounds Rd"], "city": "Ashland City", "state": "TN", "zip": "37015"}, "phone": "866-442-5301"}
{"id": "ff03874f-f66a-eb11-a812-001dd800ac9e", "title": "Williamson County Ag Park - First Dose", "lat": 35.86465, "long": -86.82605, "address": {"lines": ["4215 Long Lane"], "city": "Franklin", …
```

Parse vaccinate_gov for TN

---

vaccine_feed_ingest/runners/ky/govstatus/normalize.py

|-|
| Resolves #176 |
State: ky |
Site: govstatus |
* Uses new parent_organization enum "kroger" (please add to wiki).
```json
{"id": "ky:govstatus:48", "name": "TJ Health Columbia", "address": {"street1": "901 Westlake Drive", "street2": null, "city": "Columbia", "state": "KY", "zip": "42728"}, "location": {"latitude": 37.096814, "longitude": -85.294848}, "contact": [{"contact_type": "booking", "phone": "(270) 384-4753", "website": null, "email": null, "other": null}, {"contact_type": null, "phone": null, "website": "https://www.tjregionalhealth.org/vaccine/", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": [], …
```

normalize ky:govstatus

---

vaccine_feed_ingest/runners/ny/nyc_arcgis/normalize.py

|-|
| Resolves #55  |
State: ny |
Site: arcgis |
I'm not a python developer so please feel free to suggest drastic changes ;)
I also know nothing about ArcGIS.
Basically: this was copypasta-driven-development.
In many places I assume that the input has a certain type; it might crash if that assumption is broken by some feed updates. Should I add a try-catch or something around the `_get_normalized_location` function?
```json
{"id": "nyc_arcgis:a0e4V000008NNRlQAO", "name": "RendrCare: Chinatown Medical Physician", "address": {"street1": "86 Bowery", "street2": "4 Floor", "city": "Manhattan", "state": "NY", "zip": "10013"}, "location": {"latitude": 40.7171732, "longitude": -73.9957944}, "contact": [{"contact_type": "general", "phone": "(646) 601-6229", "website": null, …
```

Add normalize step for ny/nyc_arcgis (#55)

---

vaccine_feed_ingest/runners/ca/los_angeles_gov/fetch.sh
vaccine_feed_ingest/runners/ca/los_angeles_gov/parse.py

|-|
| Resolves #270 |
State: ca |
Site: los_angeles |
* none
```json
{"id": 25, "xParent": 15, "NumChildren": 0, "inactive": "", "organization": "Reported", "name": "Crenshaw Clinic", "addr1": "1261 W 79th Street", "addr2": "Los Angeles, CA 90044", "vaccines": "m", "logo": "", "lat-lon": "33.96669248204296,-118.29743217895289", "lat": 33.96669248204296, "lon": -118.29743217895289, "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.96669248204296%2C-118.29743217895289&z=16", "notes": "Run by LA City Fire Dept.", "notesSpn": "Dirigido por Departamento de Bomberos de la ciudad de Los \u00c1ngeles", "alt": "Tues-Sat 8am-4pm", "altSpn": "martes-s\u00e1bado 8am-4pm", "date": "", "time": "", "link": …
```

Ca los angeles gov parse

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/la/tableau/parse.py

|-|
| Resolves #95 |
State: la |
Site: tableau |
Depends on #229. Partial duplicated work of #232.
```json
{"contact": {"phone": "(337) 684-4262"}, "name": "Acadia St. Landry Hospital", "address": {"street1": "810 S Broadway Street", "city": "Church Point", "state": "LA"}, "minimum_age": 16}
{"contact": {"website": "http://www.dgwfamilyclinic.com", "phone": "(337) 514-5065"}, "name": "Dennis G. Walker Family Clinic", "address": {"street1": "421 North Avenue F", "city": "Crowley", "state": "LA"}, "minimum_age": 16}
{"contact": {"website": "https://www.walgreens.com/covid19vac"}, "name": "Walgreens #09862", "address": {"street1": "1204 The Boulevard", "city": "Rayne", "state": "LA"}, "minimum_age": 16}
{"contact": {"website": "https://www.walgreens.com/covid19vac"}, "name": …
```

Add parser for la/tableau

---

vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py

Related to #233 
@eliblock Just noticed this one bug I missed in #276

quick fix to use typed helpers for the Inventory attr

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/ingestors/arcgis_ingest.py
vaccine_feed_ingest/utils/normalize.py

- Upgrade Black to latest `21.4b2`: https://github.com/psf/black/blob/master/CHANGES.md
- Upgrade Pathy to latest `0.5.2`: https://github.com/justindujardin/pathy/blob/master/CHANGELOG.md

Upgrade dependancies to latest

---

vaccine_feed_ingest/runners/ak/arcgis/normalize.py
vaccine_feed_ingest/runners/az/arcgis/normalize.py
vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py
vaccine_feed_ingest/runners/in/arcgis/normalize.py
vaccine_feed_ingest/runners/ky/govstatus/normalize.py
vaccine_feed_ingest/runners/me/maine_gov/normalize.py
vaccine_feed_ingest/runners/mo/arcgis/normalize.py
vaccine_feed_ingest/runners/nc/myspot_gov/normalize.py
vaccine_feed_ingest/runners/pa/arcgis/normalize.py
vaccine_feed_ingest/runners/ri/arcgis/normalize.py
vaccine_feed_ingest/runners/sc/arcgis/normalize.py

Use underscores rather than colons in authorities

---

vaccine_feed_ingest/cli.py
vaccine_feed_ingest/stages/ingest.py
vaccine_feed_ingest/stages/site.py

Migrated from #285 on behalf of @shashank025 
|-|
| Resolves #255 |
State:  |
Site:  |
NA
Ran `all-stages` for `ak/arcgis`via:
```
poetry run vaccine-feed-ingest all-stages ak/arcgis
```
and examined the first line of normalization output via:
```
head -1 out/ak/arcgis/normalized/2021-04-28T22\:44\:45/d92cbd6ff2524d7e92bef109f30cb366_0.parsed.normalized.ndjson
```
```json
{"id": "ak:arcgis:d92cbd6ff2524d7e92bef109f30cb366_0:85b07ac7-c9b6-4d09-83ec-a720998c2fbf", "name": "North Slope Borough Public Health Nursing-Wellness", "address": {"street1": "579 Kongosak St", "street2": null, "city": "Barrow", "state": "AK", "zip": "99723"}, "location": {"latitude": 71.29069998454801, "longitude": -156.7920099649541}, "contact": [{"contact_type": null, "phone": "(907) 852-0270", …
```

refactor: shared code to determine executable and config

---

vaccine_feed_ingest/runners/la/tableau/normalize.py
vaccine_feed_ingest/runners/la/tableau/parse.py
vaccine_feed_ingest/utils/parse.py

|-|
| Resolves #96  |
State: LA |
Site: tableau |
The parsed file contained no ids, so I'm using e.g. `walgreens:9862` when possible, and falling back to the location name.
Hooray for `tox`!
```json
{"id": "Acadia St. Landry Hospital", "name": "Acadia St. Landry Hospital", "address": {"street1": "810 S Broadway Street", "street2": null, "city": "Church Point", "state": "LA", "zip": null}, "location": null, "contact": [{"contact_type": "general", "phone": "(337) 684-4262", "website": null, "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": "la:tableau", "id": "Acadia St. Landry …
```

Normalize tableau from Louisiana (#96)

---

vaccine_feed_ingest/runners/az/pinal_ph_clinics_gov/fetch.py

|-|
| Resolves #280 |
State: AZ |
Site: AZ |
N/A - raw html
```sh
poetry run vaccine-feed-ingest fetch --state az
```

Fetch pinal_ph_clinics_gov for AZ

---

vaccine_feed_ingest/runners/az/pinal_ph_clinics_gov/parse.py

|-|
| Resolves #282 |
State: AZ |
Site: pinal_ph_clinics_gov |
```json
{"Clinic": "Apache Junction Clinic", "Address": "575 N Idaho Rd, Ste 301 Apache Junction, AZ 85119", "City": "Apache Junction", "Nursing Hours": "Tuesday to Friday 8am-6pm", "WIC Hours": "Tuesday to Friday 8am-6pm", "Phone Number": "1-866-960-0633"}
{"Clinic": "Casa Grande Clinic", "Address": "1729 N Trekell Rd, Ste 120 Casa Grande, AZ 85122", "City": "Casa Grande", "Nursing Hours": "Monday to Friday 8am-6pm", "WIC Hours": "Monday to Friday 8am-6pm", "Phone Number": "1-866-960-0633"}
{"Clinic": "Coolidge Clinic", "Address": "119 W Central\n                    Coolidge, AZ 85128", "City": "Coolidge", "Nursing Hours": "Thursday to Friday 8am-6pm", "WIC Hours": "Thursday to Friday 8am-6pm", "Phone Number": …
```

Parse pinal_ph_clinics_gov for AZ

---

vaccine_feed_ingest/runners/mo/arcgis/normalize.py
vaccine_feed_ingest/runners/sc/arcgis/normalize.py

Fixes `sc/arcgis` and `mo/arcgis`

Fix `sc/arcgis` and `mo/arcgis` normalizers

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/co/colorado_gov/fetch.py
vaccine_feed_ingest/runners/co/colorado_gov/parse.py

|-|
| Resolves #261 |
State:  CO |
Site: colorado_gov  |
I found a way to fetch a more parsable format than the inline JS, so hopefully this approach is ok.
To find the KML URL
1. Open the [google map](https://www.google.com/maps/d/viewer?mid=1x9KT3SJub0igOTnhFtdRYmceZuBXMWvK&ll=38.98747216882165,-105.9556642978642&z=6)  in a browser and open the Network Tab in dev tools
2. Open the menu in the header of the google maps viewer, probably 3 vertical dots
3. Choose Download KML and in the popup dialog select "Export as KML instead of KMZ. Does not support all icons."
4. You will be prompted to save the file somewhere, cancel that as it's not important right now
5. Back in the Network Tab you should see a URL like the following: …

Parse colorado_gov for CO

---

.github.dependabot.yml

Enable non-security Dependabot updates

chore(deps): enable dependabot

---

vaccine_feed_ingest/runners/me/maine_gov/normalize.py

|-|
| Resolves #236 |
State: me |
Site: maine_gov |
* Area code 207 is the only area code in Maine, so let's assume that when given a 7-digit phone number
```json
{"id": "me_maine_gov:bridgton_hospital_bridgton", "name": "Bridgton Hospital", "address": null, "location": null, "contact": [{"contact_type": "general", "phone": "(207) 520-2917", "website": null, "email": null, "other": null}, {"contact_type": "general", "phone": null, "website": "https://www.cmhc.org/about-us/cmh-alert/vaccine-covid-19/", "email": null, "other": null}, {"contact_type": "booking", "phone": "(207) 520-2917", "website": null, "email": null, "other": null}, {"contact_type": "booking", "phone": null, "website": "https://www.cmhc.org/about-us/cmh-alert/vaccine-covid-19/", "email": null, "other": …
```

Me maine gov normalize  add area codes

---

vaccine_feed_ingest/runners/tn/vaccinate_gov/normalize.py

|-|
| Resolves #249 |
State: tn |
Site: vaccinate_gov |
* this dataset produces duplicates when a single location offers multiple vaccine types, or offers both first and second doses. we make no effort to deduplicate them here, though lat/long should be sufficient to do so downstream.
```json
{"id": "tn:vaccinate_gov:0048c3cd-cd76-eb11-a812-001dd801407a", "name": "Cheatham County Second Dose Moderna POD", "address": {"street1": "870 Fairgrounds Rd", "street2": null, "city": "Ashland City", "state": "TN", "zip": "37015"}, "location": {"latitude": 36.26931, "longitude": -87.04256}, "contact": [{"contact_type": null, "phone": "(866) 442-5301", "website": null, "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": …
```

tn vaccinate gov normalize

---

vaccine_feed_ingest/runners/az/pinal_ph_clinics_gov/normalize.py

|-|
| Resolves #284 |
State: az |
Site: pinal_ph_clinics_gov |
* none
```json
{"id": "az_ph_pinal_clinics_gov:apache_junction_clinic_apache_junction", "name": "Apache Junction Clinic", "address": {"street1": "575 N Idaho Rd", "street2": "Ste 301", "city": "Apache Junction", "state": "AZ", "zip": "85119"}, "location": null, "contact": [{"contact_type": null, "phone": "(866) 960-0633", "website": null, "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": [{"day": "tuesday", "opens": "08:00", "closes": "18:00"}, {"day": "wednesday", "opens": "08:00", "closes": "18:00"}, {"day": "thursday", "opens": "08:00", "closes": "18:00"}, {"day": "friday", "opens": "08:00", "closes": "18:00"}], "availability": null, "inventory": null, "access": null, …
```

normalize pinal_ph_clinics_gov for az

---

vaccine_feed_ingest/runners/ny/northwell_health/normalize.py

|-|
| Resolves #319  |
State: ny |
Site: northwell_health |
Much of the script for this one is adapted from [normalize tn/vaccinate_gov](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/685003c7a95a5f2f4ab1b23d63ba5652be3bd3ba/vaccine_feed_ingest/runners/tn/vaccinate_gov/normalize.py). 
```json
{"id": "ny_northwell_health:18", "name": "Nassau - Belmont (2150 Hempstead Tpk)", "address": {"street1": "2150 Hempstead Turnpike", "street2": null, "city": "Elmont", "state": "NY", "zip": "11722"}, "location": {"latitude": 40.7095, "longitude": -73.7204}, "contact": [{"contact_type": null, "phone": null, "website": "https://northwellvaccine.force.com/s/?id=a1T4x000007TWHNEA4", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": …
```

Add normalize ny/northwell_health

---

vaccine_feed_ingest/runners/az/arcgis/normalize.py
vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py
vaccine_feed_ingest/runners/nv/immunizenevada_org/normalize.py
vaccine_feed_ingest/runners/ny/nyc_arcgis/normalize.py

Resolves #342 
Resolves #341 
Resolves #340 
Resolves #334

Fix a bunch of normalizers

---

vaccine_feed_ingest/runners/ca/los_angeles_gov/normalize.py

|-|
| Resolves #271 |
State: CA |
Site: los_angeles_gov |
1. There were no usable ids in the source data, so I derive them from location names.
2. There are no phone numbers! Is this useful at all?
3. The human-legible source for this data seems to be https://www.google.com/maps/d/u/0/viewer?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=34.1884094%2C-118.5796803&z=10, but I put the URL to the .js file from the fetch step in the `source` field. Is there somewhere I should add the Google Maps link?
```json
{"id": "ca_los_angeles_gov:hansen_dam_recreational_center", "name": "Hansen Dam Recreational Center", "address": {"street1": "11798 Foothill Blvd.,", "street2": null, "city": "Lake View Terrace, CA", "state": "CA", "zip": "91342"}, "location": {"latitude": 34.27136269999998, …
```

Normalize ca/los_angeles_gov (#271)

---

vaccine_feed_ingest/cli.py
vaccine_feed_ingest/stages/ingest.py

Add flag, `--fail-on-runner-error` or `--no-fail-on-runner-error` (default is former). When set to `--fail-on-runner-error`, subprocess errors or validation errors will raise. When set to `--no-fail-on-runner-error`, subprocess errors or validation errors will be logged but ignored.
In the worker we will set `--no-fail-on-runner-error` so that we can process even if individual sites fail.

feat: flag for heeding or skipping runner errors

---

vaccine_feed_ingest/runners/al/arcgis/normalize.py

|-|
| Resolves #60 |
State: al |
Site: arcgis |
This is a big one. There are four different input files that are each structured a bit differently. To handle this, I've added four different normalization functions, each returning a different `location.NormalizedLocation`.
Each input file has an associated layer and id, corresponding to [al/arcgic/fetch.yml](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/runners/al/arcgis/fetch.yml).
| Layer | id |
|---|---|
Providers | 51d4c310f1fe4d83a63e2b47acb77898 |
FederalPartners | 8f23e1c3b5c54198ab60d2f729cb787d
ApptOnly2 | d1a799c7f98e41fb8c6b4386ca6fe014
DriveThruWalkIn | 8537322b652841b4a36b7ddb7bc3b204
Much of the input data is quite variable - especially the ApptOnly2 and …

Normalize al/arcgis

---

tests/utils/test_provider_id_from_name.py
vaccine_feed_ingest/runners/co/colorado_gov/normalize.py
vaccine_feed_ingest/utils/normalize.py

|-|
| Resolves #262 |
State: CO |
Site: colorado_gov |
1. For the six Community Vaccination Sites, there is hardly any structured data. Instead of hardcoding contact info, or trying to parse it, I just put the free-form data in the Notes section.
2. There is no contact info for "Federal Retail Pharmacies". I try falling back on a store page on the chain's website, or the generic store locator page.
3. Still, over a dozen locations have no contact info at all. ~I exclude them from the output, but log a warning.~
```json
{"id": "co_colorado_gov:colorado_state_fairgrounds_community_vaccination_site", "name": "Colorado State Fairgrounds: Community Vaccination Site", "address": {"street1": null, "street2": null, "city": null, "state": "CO", "zip": null}, "location": null, …
```

Add normalize step for co/colorado_gov (#262)

---

tests/stages/test_enrichment.py
vaccine_feed_ingest/stages/enrichment.py

Add concordance link for source in enrichment stage if one is missing

Enrich concordance links with a link for source if one is missing

---

vaccine_feed_ingest/runners/dc/district/fetch.sh

|-|
| Resolves #374 |
State: DC |
Site: district |
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML+RDFa 1.1//EN">
<html lang="en" dir="ltr" version="HTML+RDFa 1.1"
xmlns:content="http://purl.org/rss/1.0/modules/content/"
xmlns:dc="http://purl.org/dc/terms/"
xmlns:foaf="http://xmlns.com/foaf/0.1/"
```
- [ :white_check_mark: ] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ :white_check_mark: ] I ran auto-formatting: `poetry run tox -e lint-fix`

fetch dc/district

---

vaccine_feed_ingest/runners/pa/arcgis/normalize.py

|-|
| Resolves #346 |
State: PA |
Site: arcgis |
```json
{"id": "pa_arcgis:5b874ac0947347e9be49f6847eb44604_0_1051", "name": "Evergreen Pharmacy II Inc", "address": {"street1": "702 Dekalb Pike", "street2": null, "city": "Blue Bell", "state": "PA", "zip": "19422"}, "location": {"latitude": 40.170035999999996, "longitude": -75.286948}, "contact": [{"contact_type": null, "phone": "(610) 616-0608", "website": null, "email": null, "other": null}, {"contact_type": null, "phone": null, "website": "https://evergreenpharmrx.com/", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": …
```

Fix Normalize arcgis for PA

---

vaccine_feed_ingest/cli.py
vaccine_feed_ingest/stages/load.py
vaccine_feed_ingest/vial.py

Can configure import batch size to VIAL. This may help with uploading VF.
1. Flag: `--import-batch-size=500`
2. Env: `IMPORT_BATCH_SIZE=500`

Add configurable import batch size

---

vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/normalize.py

Work in progress. Current progress documented in the linked issue
fixes #121

Add normalizer for GISCorps national vaccine providers

---

vaccine_feed_ingest/runners/mn/gov/parse.yml

|-|
| Resolves #537 |
State: MN |
Site: gov |
They're calling vaccination `Testing`, sigh.
```json
{"attributes": {"AdditionalHoursInfo": null, "AddrLine1": "120 ELTON HILLS DRIVE NW", "City": "ROCHESTER", "County": "OLMSTED", "EndDate": null, "FridayEnd": "6:00pm", "FridayStart": "9:00am", "MondayEnd": "6:00pm", "MondayStart": "9:00am", "OBJECTID": 419, "Phone": "(507) 322-6124", "ProviderName": "ROCHESTER COMMUNITY PHARMACY", "SaturdayEnd": "2:00pm", "SaturdayStart": "10:00am", "SiteName": "Rochester Community Pharmacy - Elton Hills Drive", "StartDate": null, "State": "MN", "SundayEnd": "Closed", "SundayStart": "Closed", "TestingOptions": "Indoor vaccination", "TestingRequirements": "Appointment", "TestingTypes": "COVID-19 Vaccine", "ThursdayEnd": "6:00pm", …
```

Parse mn.gov for MN

---

vaccine_feed_ingest/runners/tx/arcgis/normalize.py

|-|
| Resolves #51  |
State: tx |
Site: arcgis |
Rebase https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/191 and use the new schema
`$ head -1 out/tx/arcgis/normalized/2021-05-06T18:29:30/* |jq`
```json
{
"id": "tx_arcgis:3078b524189848569f62985d71f4584b_0_1",
"name": "Walgreens Pharmacy 04836",
"address": {
"street1": "11810 RANCH ROAD 620 N",
"street2": null,
"city": "Austin",
"state": "TX",
"zip": "78750"
},
"location": {
"latitude": 30.46234613500007,
"longitude": -97.82375806399995
},
"contact": [
{
"contact_type": "booking",
"phone": "(512) 258-2459",
"website": null,
"email": null,
"other": null
},
{
"contact_type": "booking",
"phone": null,
"website": "https://www.walgreens.com/locator/walgreens-11810+ranch+road+620+n-austin-tx-78750/id=4836", …
```

Fixup PR #191 (Normalize tx)

---

vaccine_feed_ingest/stages/load.py
vaccine_feed_ingest/vial.py

Followup to #557, to fix the error about `raise_for_status`:

fix(import_source_locations): Error about missing raise_for_status

---

vaccine_feed_ingest/runners/az/arcgis/normalize.py
vaccine_feed_ingest/runners/sc/arcgis/normalize.py

Observed some quirks while running normalizers (in both cases due to typos in upstream data). Fix `az/arcgis` and `sc/arcgis` to be a bit more resilient.

fix: small fixes to a couple normalizers

---

tests/utils/test_match.py
vaccine_feed_ingest/utils/match.py

Handle the case where source has no contact info, and add a test for that case

Fix evaluating phone numbers when source is missing contacts

---

vaccine_feed_ingest/runners/sd/arcgis/fetch.yml

|-|
| Resolves #486 |
State: SD |
Site: arcgis |
```json
{
"features": [
{
"attributes": {
"EditDate": null,
"GlobalID": "4dd5c027-89c2-4644-91fa-e48245a109c3",
"OBJECTID": 464,
"acceptsinsurance": null,
"agencyurl": "https://www.walmart.com/cp/1228302",
"comments": null,
"email": null,
"facebook": null,
"facilityarea": null,
"facilityid": null,
"factype": "Pharmacy",
"fulladdr": "2791 DAKOTA AVE S",
"imageurl": null,
"instagram": null,
"layer_id": 0,
"municipality": "HURON",
"name": "WALMART PHARMACY #3853",
"operhours": null,
"phone": null,
```

Fetch ArcGIS for SD

---

vaccine_feed_ingest/runners/sd/arcgis/fetch.yml
vaccine_feed_ingest/runners/sd/arcgis/parse.yml

|-|
| Resolves #506 |
State: SD |
Site: arcgis |
```json
{"attributes": {"EditDate": null, "GlobalID": "4dd5c027-89c2-4644-91fa-e48245a109c3", "OBJECTID": 464, "acceptsinsurance": null, "agencyurl": "https://www.walmart.com/cp/1228302", "comments": null, "email": null, "facebook": null, "facilityarea": null, "facilityid": null, "factype": "Pharmacy", "fulladdr": "2791 DAKOTA AVE S", "imageurl": null, "instagram": null, "layer_id": 0, "municipality": "HURON", "name": "WALMART PHARMACY #3853", "operhours": null, "phone": null, "pubview": "Yes", "service_item_id": "3bb3f167d57149ef8027a68a609edc2d", "status": null, "twitter": null, "waittime": null, "walkins": null}, "geometry": {"spatialReference": {"latestWkid": 4326, "wkid": 4326}, "x": -98.214367, "y": 44.33447799999999}} …
```

Parse ArcGIS for SD

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/dc/district/normalize.py

|-|
| Resolves #428 |
State: DC |
Site: district |
Pulled in dateparser to get a valid date out of, eg. "May 27".
```json
{"id": "dc_district:5fc514eb48024682b05f5b80136cd4b0", "name": "Arena Stage", "address": {"street1": "1101 6th St SW", "street2": null, "city": "Washington", "state": "DC", "zip": null}, "location": null, "contact": null, "languages": null, "opening_dates": null, "opening_hours": [{"day": "thursday", "opens": "08:00", "closes": "12:00"}, {"day": "friday", "opens": "08:00", "closes": "12:00"}, {"day": "saturday", "opens": "08:00", "closes": "12:00"}, {"day": "sunday", "opens": "08:00", "closes": "12:00"}, {"day": "thursday", "opens": "13:00", "closes": "17:00"}, {"day": "friday", "opens": "13:00", "closes": "17:00"}, {"day": "saturday", "opens": "13:00", …
```

normalize dc/district

---

vaccine_feed_ingest/runners/ct/state/parse.py

|-|
| Resolves #498  |
State: CT |
Site: parse |
```json
{"number": 72490171, "name": "Stoll's Pharmacy, Inc. COVID-19 Vaccine Clinic", "agency_id": 72490165, "created_at": "2021-04-22T09:21:15.728-04:00", "updated_at": "2021-04-22T09:36:15.712-04:00", "description": "Please see below (or click on the \u2018More Details\u2019 button) for information about which groups are currently being vaccinated, how to schedule an appointment, and other important details about this vaccination location.<br><br><u>Site Name</u>: Stoll's Pharmacy - Waterbury<br><u>Address</u>: 185 Grove Street, Waterbury, CT 06710<br><u>Vaccine Eligibility</u>: Click <a href=\"https://portal.ct.gov/Coronavirus/COVID-19-Vaccination---Phases\" target=\"_blank\" rel=\"noopener\"><strong>here …
```

add parser for ct/state

---

vaccine_feed_ingest/runners/il/ilvaccine_org/fetch.sh

|-|
| Resolves #313 |
State: `il` |
Site: `ilvaccine_org` |
This is already parsed, making #314 easier (simply needs to copy files)
I work on ILVaccine.org and created the original data feed.
```ndjson
{"id":"ilvaccine_org:rec5FTKvH6e2hoUZm","name":"Advocate Condell Medical Center COVID-19 Vaccine Center","address":"700 Garfield Ave\nLibertyville, IL 60048","contact":[{"website":"https://www.advocateaurorahealth.org/coronavirus-disease-2019/covid19-vaccine"}],"notes":["Advocate Aurora Health is now vaccinating anyone in Illinois who’s 16 and older – whether you’re their patient or not."],"source":{"source":"ilvaccine_org","id":"rec5FTKvH6e2hoUZm"}}
{"id":"ilvaccine_org:recDbPEdMZ81yL0Wy","name":"Advocate Emergency Medical Services Academy COVID-19 Vaccine …
```

Create fetch.sh for ILVaccine.org

---

vaccine_feed_ingest/runners/ia/state/fetch.py

|-|
| Resolves #379  |
State: ia |
Site: state |
Implement fetcher for ia/state
```json
{'Success': True,
'Message': '',
'Result': '[{"MilesAway":0.0,"Distance":175.5,"StartingLat":"42.03205000","StartingLng":"-93.59139000","ProviderID":147,"ProviderName":"Wagner Pharmacy","Phone":"(563) 242-0626","Address1":"1726 N. 2nd Street","City":"Clinton","State":"IA","Zipcode":"52732","County":"","websiteurl":"https://www.wagnerpharmacies.com","WebpageSurveyResponse":"","ActiveFlag":true,"LatCoord":"41.86476","LngCoord":"-90.18307","CreatedBy":"","CreateDate":null,"ModifiedBy":"","ModifyDate":null},{"MilesAway":0.0,"Distance":175.4,"StartingLat":"42.03205000","StartingLng":"-93.59139000","ProviderID":144,"ProviderName":"Clinton County Public Health- Genesis VNA","Phone":"(563) …
```

Issue-379: Implement fetcher for ia/state

---

vaccine_feed_ingest/runners/fl/state/parse.py

|-|
| Resolves #403 |
State: FL |
Site: state |
```json
{"id": "34416", "title": "Southern Internal Medicine", "address": "404 NW Hall of Fame Dr", "source": "manual", "content": "", "location": {"icon": "https://floridahealthcovid19.gov/wp-content/plugins/wp-google-map-gold/assets/images/default_marker.png", "lat": "30.18410951353843", "lng": "-82.69534913079957", "city": "Lake City", "state": "FL", "country": "United States", "onclick_action": "marker", "redirect_custom_link": "", "marker_image": "/wp-content/themes/wordpress-template/assets/images/pin_orange.png", "open_new_tab": "yes", "postal_code": "32055", "draggable": false, "infowindow_default_open": false, "animation": "", "infowindow_disable": true, "zoom": 5, "extra_fields": {"%ef%bb%bfcounty-name": "", …
```

Parse fl/state

---

vaccine_feed_ingest/runners/mn/gov/normalize.py

Normalize mn.gov for MN
|-|
| Resolves #540 |
State: mn |
Site: gov |
```json
{"id": "mn_gov:18279cf4ab4740ae92708db437250056_0_76ed1b33-22f3-4d74-81ca-1b0f6bbb286a", "name": "Rochester Community Pharmacy - Elton Hills Drive", "address": {"street1": "120 ELTON HILLS DRIVE NW", "street2": null, "city": "ROCHESTER", "state": "MN", "zip": "55901"}, "location": {"latitude": 44.04167599232946, "longitude": -92.46359100214372}, "contact": [{"contact_type": null, "phone": "(507) 322-6124", "website": null, "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": [{"day": "monday", "opens": "09:00", "closes": "18:00"}, {"day": "tuesday", "opens": "09:00", "closes": "18:00"}, {"day": "wednesday", "opens": "09:00", "closes": "18:00"}, {"day": …
```

normalize mn/gov

---

vaccine_feed_ingest/runners/wa/state/parse.py

|-|
| Resolves #499 |
State: WA |
Site: State |
Pretty simple because fetch is json. Just get's the locations and newline's them into `.ndjson`
```json
{"locationId": "recT5VYLb0qwyVTSz", "locationName": "North Basin - Davenport", "locationType": null, "providerId": null, "providerName": null, "departmentId": null, "departmentName": null, "addressLine1": "100 3rd Street", "addressLine2": null, "city": "Davenport", "state": "Washington", "county": "Lincoln", "zipcode": "99122", "latitude": 47.65713, "longitude": -118.14546, "description": null, "contactFirstName": null, "contactLastName": null, "fax": null, "phone": "(509) 725-7501", "email": null, "schedulingLink": "https://www.lincolnhospital.org/health-resources/covid-19-update/", "vaccineAvailability": "AVAILABLE", …
```

Add parse step for wa/state. Fixes #499

---

vaccine_feed_ingest/runners/ct/state/normalize.py

|-|
| Resolves #518 |
State: CT |
Site: state |
I'll have a followup that parses the opening hours.  They're really messy, and I don't want it to hold this up.
```json
{"id": "ct_state:72490171", "name": "Stoll's Pharmacy, Inc. COVID-19 Vaccine Clinic", "address": {"street1": "185 Grove Street", "street2": null, "city": "Waterbury", "state": "CT", "zip": "06710"}, "location": {"latitude": 41.55975, "longitude": -73.04276}, "contact": [{"contact_type": null, "phone": "203-575-0199", "website": null, "email": null, "other": null}, {"contact_type": null, "phone": null, "website": "https://StollsPharmacy.com", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": {"drop_in": null, "appointments": true}, "inventory": …
```

normalizer for ct/state

---

vaccine_feed_ingest/runners/us/carbon_health/fetch.py

Fetch Carbon Health for US
|-|
| Resolves #369 |
State: us |
Site: carbon_health |
```json
{"id":"00022250-3e2f-45e8-b897-a59ffca5181e","name":"King Soopers Pharmacy #40","phoneNumber":"3039888058","firstLine":"12043 W Alameda Pkwy","city":"Lakewood","state":"CO","zip":"80228","createdAt":1614356042104,"x":39.7086331,"y":-105.1373167,"services":[{"slug":"covid-vaccine","filters":{"locationUrl":"https://www.kingsoopers.com/i/coronavirus-update/pharmacy"}}]},
{"id":"00051c98-0348-4fd1-8658-734f1aa4d9b1","name":"Walgreens Co. #12426","phoneNumber":"3122801599","firstLine":"315 W CHICAGO AVE -","city":"CHICAGO","state":"IL","zip":"60654-5105","createdAt":1617263794586,"x":41.8963754,"y":-87.6364633,"services":[{"slug":"covid-vaccine","filters":{"locationUrl":"https://www.walgre …
```

fetch us/carbon_health

---

vaccine_feed_ingest/runners/us/carbon_health/parse.yml

Parse Carbon Health for US
|-|
| Resolves #371|
State: us|
Site: carbon_health|
Depends on #598
```json
{"id": "00022250-3e2f-45e8-b897-a59ffca5181e", "name": "King Soopers Pharmacy #40", "phoneNumber": "3039888058", "firstLine": "12043 W Alameda Pkwy", "city": "Lakewood", "state": "CO", "zip": "80228", "createdAt": 1614356042104, "x": 39.7086331, "y": -105.1373167, "services": [{"slug": "covid-vaccine", "filters": {"locationUrl": "https://www.kingsoopers.com/i/coronavirus-update/pharmacy"}}]}
{"id": "00051c98-0348-4fd1-8658-734f1aa4d9b1", "name": "Walgreens Co. #12426", "phoneNumber": "3122801599", "firstLine": "315 W CHICAGO AVE -", "city": "CHICAGO", "state": "IL", "zip": "60654-5105", "createdAt": 1617263794586, "x": 41.8963754, "y": -87.6364633, "services": [{"slug": …
```

parse us/carbon_health

---

vaccine_feed_ingest/runners/ri/prepmod/fetch.yml
vaccine_feed_ingest/runners/ri/prepmod/normalize.yml
vaccine_feed_ingest/runners/ri/prepmod/parse.yml

|-|
| Resolves #482 |
| Resolves #502 |
| Resolves #522 |
State: ri |
Site: prepmod |
This seemed to work out of the box using the existing prepmod infra.
two lines from normalized file:
```json
{"id": "prepmod:1915", "name": "Seaside Pharmacy", "address": {"street1": "224 Post Road", "street2": null, "city": "Westerly", "state": "RI", "zip": "02891"}, "location": null, "contact": [{"contact_type": "booking", "phone": null, "website": "https://www.vaccinateri.org//appointment/en/client/registration?clinic_id=1915", "email": null, "other": null}], "languages": null, "opening_dates": [{"opens": "2021-05-11", "closes": "2021-05-11"}], "opening_hours": [{"day": "tuesday", "opens": "09:00", "closes": "19:30"}], "availability": {"drop_in": null, "appointments": true}, …
```

add pipeline for ri/prepmod

---

vaccine_feed_ingest/runners/us/carbon_health/fetch.py

address code review comments from #598

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/wi/arcgis_map/normalize.py

Normalize ArcGIS for WI
|-|
| Resolves #99 |
State: wi |
Site: arcgis |
Not much per-site data available here.
```json
{"id": "wi_arcgis_map:wi_arcgis_map_0_1", "name": "Assisted Living Pharmacy Svc LLC", "address": {"street1": "1441 N Mayfair Rd Ste 202", "street2": null, "city": "Wauwatosa", "state": "WI", "zip": "53226"}, "location": {"latitude": 43.048292999689814, "longitude": -88.04885800009654}, "contact": [{"contact_type": null, "phone": null, "website": "https://www.alpsrx.com/", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": "wi_arcgis_map", "id": "1", …
```

normalize wi/arcgis_map

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/us/carbon_health/normalize.py

Normalize Carbon Health for US
|-|
| Resolves #373 |
State: us |
Site: carbon_health |
This is a relatively large dataset (27MB, ~46k sites), with a decent amount of data per site.
My first pass implementation was pretty slow -- ~30 seconds on my machine. I optimized it a bit and it's now at ~15 seconds. A lot of that is in validation, so it might take some doing to go faster.
```json
{"id":"us_carbon_health:00022250-3e2f-45e8-b897-a59ffca5181e","name":"King Soopers Pharmacy #40","address":{"street1":"12043 W Alameda Pkwy","street2":null,"city":"Lakewood","state":"CO","zip":"80228"},"location":{"latitude":39.7086331,"longitude":-105.1373167},"contact":[{"phone":"3039888058"},{"website":"https://www.kingsoopers.com/i/coronavirus-update/pharmacy"}],"languages":null,"opening_d …
```

normalize us/carbon_health

---

vaccine_feed_ingest/stages/enrichment.py
vaccine_feed_ingest/stages/ingest.py

Add additional log messages explaining issues that come up during enrichment.

chore: failure logging in enrichment

---

vaccine_feed_ingest/runners/la/tableau/normalize.py
vaccine_feed_ingest/runners/la/tableau/parse.py

|-|
| Resolves #621 |
State: la |
Site: tableau |
Allows for bad input row; see comment in the diff.
```json
{"id": "acadia_st_landry_hospital", "contact": {"phone": "(337) 684-5435"}, "name": "Acadia St. Landry Hospital", "address": {"street1": "810 S Broadway Street", "city": "Church Point", "state": "LA"}, "minimum_age": 16}
{"id": "dennis_g_walker_family_clinic", "contact": {"website": "http://www.dgwfamilyclinic.com", "phone": "(337) 514-5065"}, "name": "Dennis G. Walker Family Clinic", "address": {"street1": "421 North Avenue F", "city": "Crowley", "state": "LA"}, "minimum_age": 16}
{"id": "walmart_pharmacy_310_crowley", "contact": {"website": "https://www.walmart.com/covidvaccine"}, "name": "Walmart Pharmacy #310 - Crowley", "address": {"street1": "729 Odd Fellows …
```

Fix la/tableau parse.py

---

vaccine_feed_ingest/runners/ia/state/normalize.py

|-|
| Resolves #432  |
State: IA |
Site: State |
```json
{"id": "ia_state:147", "name": "Wagner Pharmacy", "address": {"street1": "1726 N. 2nd Street", "street2": null, "city": "Clinton", "state": "IA", "zip": "52732"}, "location": {"latitude": 41.86476, "longitude": -90.18307}, "contact": [{"contact_type": null, "phone": null, "website": "https://www.wagnerpharmacies.com", "email": null, "other": null}, {"contact_type": null, "phone": "(563) 242-0626", "website": null, "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": true, "source": {"source": "ia_state", "id": "147", "fetched_from_uri": …
```

ISSUE-432: Add ia/state normalizer

---

vaccine_feed_ingest/cli.py
vaccine_feed_ingest/stages/ingest.py

Add a `--api-cache`/`--no-api-cache` flag (defaults to `--api-cache`). If the flag is set to `--no-api-cache`, enrichment is run _without_ the cache.

feat: --api-cache flag to control cache in enrich

---

.github/workflows/lint.yml
setup.sh
vaccine_feed_ingest/runners/al/jefferson/parse.py

|-|
| Resolves #184 |
State: AL |
Site: Jefferson County |
* The Jefferson County data is [a PDF](https://www.jcdh.org/SitePages/Misc/PdfViewer?AdminUploadId=1368). To parse it, this PR uses one of the strategies agreed on in the discussion on #184:
* Use `pdftohtml`, invoked from Python, to convert the PDF into XML.
* Use `lxml` to process the XML in Python into NDJSON.
* The document does not have a consistent structure for separating each vaccine provider and site, only header images for each provider (which are not parsed as text).
* This PR uses line-spacing heuristics to group XML lines of text into vaccine providers
and vaccine sites for each provider.
* This is arguably the most complex part of the parsing logic, found in the function `_group_text_by_provider`. I …

Create parser for Jefferson County PDF from AL (#184)

---

vaccine_feed_ingest/stages/enrichment.py
vaccine_feed_ingest/stages/ingest.py
vaccine_feed_ingest/vial.py

This is to fix the log statements to sat we processed 1 file instead of 0 files.

Fix off by one errors by starting enumerate at 1

---

vaccine_feed_ingest/apis/placekey.py
vaccine_feed_ingest/stages/enrichment.py

Collect all of the locations and pas them all at once to bulk api. Their library will batch into groups of 100, so I don't need to.
I think we can enable place keys after this lands!

Add placekeys with bulk API which is way faster

---

poetry.lock
pyproject.toml
tests/stages/test_enrichment.py
vaccine_feed_ingest/apis/geocodio.py
vaccine_feed_ingest/cli.py
vaccine_feed_ingest/stages/enrichment.py
vaccine_feed_ingest/stages/ingest.py

Calls geocodio if the address is invalid or the lat-ln is missing
https://www.geocod.io/docs/?python#batch-geocoding

Call geocodio to fix invalid addresses or add missing lat-lngs

---

vaccine_feed_ingest/runners/al/arcgis/normalize.py

Some feeds within `al/arcgis` appear to have unstable ids.
Use lat/lng + location name + address (if available) to attempt to generate stable ids. This approach has some downsides, e.g.:
* if typos are fixed in those fields, the ids will change. We expect this to be lower churn than the current unstable ids, however.
* if there are duplicate entries for a location within the data set with slightly different data, we need to handle them. Presently we drop all subsequent instances of an id once we've written the first. At the most recent run, this removed less than 10 rows of data.

fix: generate stable ids for al/arcgis

---

vaccine_feed_ingest/runners/us/va_gov/fetch.sh

|-|
| Resolves #605 |
State: US
Site: va_gov
Created as per spec from VA's API documentation. 
Requires a key that can be self-serve created on VA's website (link in code comments).
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-71.03613513,42.34459497]},"properties":{"id":"vc_0101V","name":"Boston Vet Center","facility_type":"vet_center","classification":null,"website":null,"address":{"mailing":{},"physical":{"zip":"02210-2303","city":"Boston","state":"MA","address_1":"7 Drydock Avenue","address_2":"Suite 2070","address_3":null}},"phone":{"fax":"617-261-3547","main":"857-203-6461"},"hours":{"friday":"830AM-430PM","monday":"830AM-700PM","sunday":"Closed","tuesday":"830AM-700PM","saturday":"Closed","thursday":"830AM-600PM …

Addresses issue #605 -- Fetch JSON for US/VA_GOV

---

vaccine_feed_ingest/runners/us/va_gov/parse.yml

|-|
| Resolves #607 |
State: `us` |
Site: `va_gov` |
```json
{"id": "vha_672", "type": "facility", "attributes": {"access": {"health": [{"service": "Audiology", "new": 15.922077, "established": 3.099153}, {"service": "Cardiology", "new": 30.25, "established": 11.144694}, {"service": "Dermatology", "new": 24.052631, "established": 14.273026}, {"service": "Gastroenterology", "new": 45.671641, "established": 12.838323}, {"service": "Gynecology", "new": 26.629629, "established": 1.673387}, {"service": "MentalHealthCare", "new": 4.307692, "established": 2.047023}, {"service": "Ophthalmology", "new": 26.507246, "established": 8.222222}, {"service": "Optometry", "new": 98.973684, "established": 9.745192}, {"service": "Orthopedics", "new": 17.322033, "established": 2.078341}, …
```

chore: parse `us/va_gov`

---

poetry.lock
pyproject.toml
vaccine_feed_ingest/runners/us/physicians_immediate/normalize.py
vaccine_feed_ingest/runners/us/physicians_immediate/parse.py

|-|
| Resolves #433  |
State: us |
Site: physicians_immediate |
- This isn't _quite_ complete. I haven't yet normalized store hours for the handful of sites that have them. It may be a few days before I get more time to work on this, so I wanted to get a working PR opened up rather than wait for it to be perfect. 
- I had to alter the parser to add some row ids which existed in the source HTML. I didn't realize those would be helpful when I wrote the parser. 
- ~~I'm not sure if the way I handled addresses is correct. I'm nervous that leaving the full address (including state and ZIP where available) in the `street1` field might break something downstream.~~ **FIXED (2021-05-16)**
```json
{"id": "us_physicians_immediate:31509_144", "name": "Niles", "address": {"street1": …
```

Normalize Physicians' Immediate Care for US

---

vaccine_feed_ingest/runners/al/jefferson/fetch.py
vaccine_feed_ingest/runners/al/jefferson/normalize.py
vaccine_feed_ingest/runners/al/jefferson/parse.py

|-|
| Resolves https://github.com/CAVaccineInventory/vaccine-feed-ingest/issues/185 |
State: AL |
Site: jefferson |
- Commit-wise review is recommended.
- There are a few preparatory changes to the fetch and parse steps to make extra metadata available to the normalize step:
- Fetch: Record an extra JSON metadata file containing the fetched URL in `fetched_from_uri`, so that later steps can access it.
- Parse: Pass along `fetched_from_uri`.
- Parse: Extract the `published_at` date from the PDF. This required a slight refactoring to compute the list of vaccine sites up front, while scanning them for a line of the form `UPDATED May 25, 2021`.
- This PR then introduces the normalize step for this region, which does the following:
- Process the list of `details` for each site, …

AL: Normalize Jefferson County PDF data

---

vaccine_feed_ingest/runners/us/getmyvax_org/fetch.py

|-|
| Resolves GetMyVax.org Fetch Stage |
State: us|
Site: getmyvax_org |
Followed the spec from their docs here: https://getmyvax.org/docs/#/paths/~1api~1edge~1locations.ndjson/get
1. Grabbed locations by state because one file is very large, and by state is easier to inspect and debug.
2. I didn't encounter any `__next__` pagination so I wasn't able to verify that my pagination solution actually works :-/
Split into files by state with state initials e.g. va.ndjson, vi.ndjson
```json
{"id":"1acf030f-c889-41f0-babc-a58575a93056","provider":"CVS","location_type":"PHARMACY","name":"CVS #10019","address_lines":["3908 N. STATELINE AVE."],"city":"TEXARKANA","state":"AR","postal_code":"71854","county":null,"position":null,"info_phone":null,"info_url":null,"booking_phone":"888-60 …
```

Fetch locations from getmyvax by state

---

vaccine_feed_ingest/runners/us/getmyvax_org/fetch.py
vaccine_feed_ingest/runners/us/getmyvax_org/parse.py

|-|
| Resolves GetMyVax.org Parse Stage |
State: us|
Site: getmyvax_org |
Since the fetched data is already in ndjson format this is almost a direct copy. I decided to strip out the appointments slots data though since it will be unused in normalize, and it takes up a lot of space and parse time.
Split into files by state with state initials e.g. va.ndjson, vi.ndjson
```json
{"id":"7f3f78a3-d9e8-406d-998f-e7556bd9e0bd","provider":"RiteAid","location_type":"PHARMACY","name":"Rite Aid #383","address_lines":["4339 Ebenezer Road"],"city":"Baltimore","state":"MD","postal_code":"21236-2143","county":null,"position":null,"info_phone":"(410) 529-6171","info_url":"https://www.riteaid.com/covid-19","booking_phone":"(410) 529-6171","booking_url":"https://www.riteaid.com/pharmacy/covid …
```

Parse GetMyVax.org

---

vaccine_feed_ingest/runners/us/getmyvax_org/normalize.py
vaccine_feed_ingest/runners/us/getmyvax_org/parse.py

|-|
| Resolves GetMyVax Normalize |
State: us |
Site: getmyvax_org |
This was a straightforward transformation. I found a couple locations that are missing cities or zipcodes, and am hoping enrichment can handle those.
The bulk of the work here was transforming the external ids into our vaccine providers.
```json
{"id":"getmyvax_org:1acf030f-c889-41f0-babc-a58575a93056","name":"CVS #10019","address":{"street1":"3908 N. STATELINE AVE.","city":"TEXARKANA","state":"AR","zip":"71854"},"contact":[{"contact_type":"booking","phone":"888-607-4287"},{"contact_type":"booking","website":"https://www.cvs.com/vaccine/intake/store/cvd-schedule"}],"availability":{"appointments":true},"links":[{"authority":"cvs","id":"10019"},{"authority":"vtrcks","id":"CV1010019"}],"source":{"source":"get …
```

Normalize GetMyVax

---

vaccine_feed_ingest/runners/la/dph/fetch.sh

|-|
| Resolves #729 resolves #746  |
State: la |
Site: dph |
simple download of an HTML file.
vaccinebot may have messed up the issues
```html
<article class="col-md-6 col-sm-12">
<h3>1st Assembly of God</h3>
<div class="info row">
<div class="date col-xs-6">
<p>Vaccine:&nbsp;<b> Pfizer or Moderna</b></p>
<p>Both Walk-in &amp; Drive-Thru</p>
<div class="secondary">
<p><span class="additional">Secondary Dose Dates:</span></p>
<p>21-28 Days Later (Pfizer and Moderna)</p>
</div>
</div>
<div class="where col-xs-6">
<div class="location">
<p>
1st Assembly of God<br>
5693 Hwy 167<br>
Winnfield, LA 71483<br>
</p>
<a href="https://www.google.com/maps/dir/?api=1&destination=5693%20Hwy%20167%2C%20Winnfield%2C%20LA" target="_blank">Get Directions</a>
<span class="call">Call To …
```

fetch la/dph

---

vaccine_feed_ingest/runners/az/maricopa_arcgis/fetch.yml
vaccine_feed_ingest/runners/az/maricopa_arcgis/parse.yml

|-|
| Resolves #728 Resolves #741 resolves #737 Resolves #748  |
State: az |
Site: maricopa_arcgis |
simple arcgis fetch and parse
vaccinebot prob messed up the issues
```json
{"attributes": {"EditDate": 1609963623553, "Editor": "ADHS_GIS_Admin", "addr1": "13677 W. McDowell Rd", "addr2": null, "adults_55_64": null, "begindate": null, "city": "Goodyear", "contact_method": "Email", "county": "Maricopa", "datetime_submitted": 1609954440000, "dose_schedule": "both", "education_childcare": "Yes", "email": "alexandra.oropeza@maricopa.gov", "enddate": null, "event_yn": "No", "first_name": "Alexandra", "fri_hrs": "8:30AM-3:00PM", "fri_open": "Yes", "full_address": null, "globalid": "e6f4249e-ff0d-4986-89f8-1ea0f25f6089", "healthcare_ems": "Yes", "last_name": "Oropeza", …
```

fetch and parse az/maricopa_arcgis

---

vaccine_feed_ingest/runners/wv/dhhr/fetch.py
vaccine_feed_ingest/runners/wv/dhhr/parse.py

|-|
| Resolves #370 |
State: WV |
Site: DHHR |
- This PR adjusts the wv/dhhr fetch script to also produce a `metadata.ndjson` file containing the fetched URI, so this can be passed along to the rest of the pipeline.
- Since the DHHR data is updated weekly, I hope this is useful information.
- This PR then parses the fetched HTML data into NDJSON, using BeautifulSoup.
- The HTML data consists of a date, followed by counties, and for each county a list of vaccine site opening hours and details. Vaccine sites may appear multiple times, on different dates. See https://dhhr.wv.gov/News/2021/Pages/COVID-19-Vaccination-Clinics-June-7-12,-2021.aspx for example.
- The general strategy is to build up a mapping `site details -> opening dates -> list of opening hours for each date`. …

Parse DHHR data for WV

---

vaccine_feed_ingest/runners/nd/state/fetch.sh

|-|
| Resolves #493  |
State: ND |
Site: State |
This appears to be the first fetcher to handle microsoft power BI data.
```json
{"jobIds":["d5e94270-deeb-4245-9e7e-6638d2a281df"],"results":[{"jobId":"d5e94270-deeb-4245-9e7e-6638d2a281df","result":{"data":{"descriptor":{"Select":[{"Kind":1,"Depth":0,"Value":"G0","GroupKeys":[{"Source":{"Entity":"VaccineLocator (3)","Property":"Provider_Address"},"Calc":"G0","IsSameAsSelect":true}],"Name":"VaccineLocator (3).Provider_Address"},{"Kind":1,"SecondaryDepth":0,"Value":"G1","GroupKeys":[{"Source":{"Entity":"VaccineLocator (3)","Property":"INVENTORY"},"Calc":"G1","IsSameAsSelect":true}],"Name":"VaccineLocator (3).INVENTORY"},{"Kind":2,"Value":"M0","Name":"Min(VaccineLocator …
```

fetch from power bi for nd/state

---

vaccine_feed_ingest/runners/nc/cone_clinics/fetch.sh

|-|
| Resolves #744 Resolves #27 |
State: nc |
Site: cone_clinics |
uses the ical url for the google calendar to get the events containing vaccination sites
```ics
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:COVID-19 Vaccine Clinics
X-WR-TIMEZONE:America/New_York
BEGIN:VEVENT
DTSTART:20210717T140000Z
DTEND:20210717T180000Z
DTSTAMP:20210608T041740Z
UID:0tmnrf2utp4plc7gml6p590576@google.com
CREATED:20210603T195818Z
DESCRIPTION:Click Here to Sign Up:<br><b><a href="https://form.jotform.com/
211574322411141" id="ow1156" __is_owner="true">Genesis Baptist Church (JOTF
ORM)</a><br><br></b><br>Pfizer<br>Johnson &amp\; Johnson
LAST-MODIFIED:20210607T155753Z
LOCATION:2812 E Bessemer Ave\, Greensboro\, …
```

fetch nc/cone_clinics

---

vaccine_feed_ingest/runners/us/getmyvax_org/fetch.py
vaccine_feed_ingest/runners/us/getmyvax_org/normalize.py

1. Update to handle external_ids as a list of tuples
2. Update to handle multiple sources for availability

Update getmyvax to support changes to external_ids and availability

---

vaccine_feed_ingest/stages/load.py
vaccine_feed_ingest/utils/misc.py
vaccine_feed_ingest/vial.py

This will hopefully fix the problem of loading not working

Stream load results into VIAL to keep memory load lower

---

vaccine_feed_ingest/runners/wv/dhhr/normalize.py
vaccine_feed_ingest/runners/wv/dhhr/parse.py

|-|
| Resolves #372 |
State: WV |
Site: DHHR |
- First commit fixes a bug in the parser, exposed by the latest data update.
- The existing parser broke on the `3<sup>rd</sup>` in the Mingo County site address in the [June 7-12 data](https://dhhr.wv.gov/News/2021/Pages/COVID-19-Vaccination-Clinics-June-7-12,-2021.aspx).
- Handle this by reading all nested text for each `<p>` into a single string, rather than iterating over `p.strings` as separate lines. This ensures we get the correct text even with inline formatting tags. Then split on `<br>` tags to obtain separate lines.
- This is mostly in the `_get_lines` function.
- This exposed an opportunity to adjust the parsing of each site's details, using regexes only where necessary, and string splitting otherwise. This doesn't …

Normalize DHHR data for WV

---

vaccine_feed_ingest/runners/ma/vaxfinder_gov/fetch.sh
vaccine_feed_ingest/runners/ma/vaxfinder_gov/parse.py

updates parsing and normalizing for ma/vaxfinder_gov whose data recently changed from XLSX to CSV
it appears as though this normalizer needs substantial work in order to add fields that are new as of this dataset since it seems as though only name and address were being added from the XLSX for whatever reason
CC @Deon as the original author of this fetcher/parser. It should be easier to get to more of the data now
```json
{"name": "Abington: CVS (Centre Ave.)", "serves": "All eligible people statewide", "address": "385 Centre Ave, Abington, MA 02351", "site_type": "Indoor", "appointment_link": "https://www.cvs.com/immunizations/covid-19-vaccine", "phone": "800-SHOP-CVS (1-800-746-7287)", "email": "", "additional_info": "", "instructions": "Check-in 15min prior", "accessibility": "", …
```

Vaxfinder data for MA is now provided as CSV

---

vaccine_feed_ingest/runners/dc/district/fetch.sh

curl is pulling in an empty HTML file for this source.
this PR updates the url to the post-redirected version

update url for dc/district source

---

vaccine_feed_ingest/runners/tx/harriscounty_gov/normalize.py

|-|
| Resolves #652  |
State: tx |
Site: harriscounty_gov |
Seems pretty standard. not much to report.
the vaccine inventory normalizer might break if it sees any value besides `Moderna` but it seems like all the sites so far only carry Moderna so that should be fine for now
```json
{"id": "tx_harriscounty_gov:c9709ff8-c8b9-4363-88b2-47f2910b6742", "name": "Bethel's Family Church", "address": {"street1": "12660 Sandpiper Dr.", "street2": null, "city": "Houston", "state": "TX", "zip": "77035"}, "location": {"latitude": 29.63934911, "longitude": -95.50383887}, "contact": [{"contact_type": null, "phone": "(832) 927-8787", "website": null, "email": null, "other": null}, {"contact_type": "general", "phone": null, "website": "https://vacstrac.hctx.net/landing", "email": null, …
```

Normalize tx/harriscounty_gov

---

vaccine_feed_ingest/runners/ca/sd_arcgis/fetch.yml
vaccine_feed_ingest/runners/ca/sd_arcgis/parse.yml

|-|
| Resolves #822 Resolves #823  |
State: ca |
Site: sd_arcgis |
standard arcgis fetch and parse
```json
{"attributes": {"DISPLAY_PUBLIC": "YES", "EditDate": 1625235150439, "GlobalID": "c19e9bd4-a82e-4111-b459-4c4e1eb34625", "Instructions": null, "Notes": "covid19vaccine@rchsd.org", "OBJECTID": 36763, "agencytype": "Walk-Thru", "county_partner_type": "County Partner - Rady's", "fulladdr": "8001 Frost Street, San Diego, CA 92123", "instructions_spanish": null, "layer_id": 0, "municipality": "San Diego", "name": "Rady Children's Hospital ", "name_spanish": "Hospital de Rady Children's", "operhours": "Monday - Saturday: 7 AM - 3 PM", "operhours_spanish": "lunes - s\u00e1bado7 AM - 3 PM", "partnership_desc": "Hospital-Based", "phone": null, "service_item_id": …
```

fetch and parse ca/sd_arcgis

---

vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py

resolves #780 by using the the `sourceSystemId` field as the id instead of `_id` (which  looks like it might be a hash, which may be why it sometimes changes)
there are also some other ids in there like for the provider that could be used in combination with maybe the name or street address to uniquely identify a record in case this id is also unstable, (but i doubt it).
In cases where this id is missing, it will use the same ID field as is currently being used and, of both are missing, it will construct an id from the street address line 1. if THAT is missing, the id will be "unknown" 
```json
{"id": "ct_covidvaccinefinder_gov:71025567", "name": "Community Health Center (Middletown)", "address": {"street1": "675 Main Street", "street2": "", "city": "Middletown", "state": "CT", "zip": …
```

stabilize ct_covidvaccinefinder_gov ID
