.github/workflows/lint.yml
As we begin to accept publicly contributed ingestion code, let's default to using [GitHub's SuperLinter](https://github.com/github/super-linter) rather than thinking through linting and formatting practices for each novel accepted language.
If we find this to be too aggressive, we can switch back to a known-desirable set of linters run in the action directly.
=> ci: SuperLinter rather than individual linters

.editorconfig, .vscode/settings.json, README.md, poetry.lock, poetry.toml, pyproject.toml, vaccine-feed-ingest/run.py, vaccine-feed-ingest/runners/_template/README.md, vaccine-feed-ingest/runners/_template/fetch.sh, vaccine-feed-ingest/runners/_template/normalize.sh, vaccine-feed-ingest/runners/_template/parse.sh, vaccine-feed-ingest/runners/ca/sf_gov/README.md, vaccine-feed-ingest/runners/ca/sf_gov/fetch.sh, vaccine-feed-ingest/runners/us/vaccinespotter_org/README.md, vaccine-feed-ingest/runners/us/vaccinespotter_org/fetch.sh, vaccine-feed-ingest/runners/us/vaccinespotter_org/normalize.sh, vaccine-feed-ingest/runners/us/vaccinespotter_org/parse.sh
1. Propose using `poetry` to handle requirement locks, packaging, and virtualenv. I think `poetry` has fewer pitfalls, so I like it better, but  I would be happy to use `Pipenv` if people are more accustomed to it.  I do want to use either `poetry` or `Pipenv` so we are all running in a consistent python environment.
2. Propose having a python wrapper that runs the fetch, parse, and normalize shell commands. That wrapper will handle the downloading, and uploading the files to GCS, and calling stages like `fetch.sh output_dir`
Note if you can also use `poetry shell` to activate the `venv` so then you can run the command directly.
- List all available sites:
```sh
poetry run vaccine-feed-ingest/run.py available-sites
```
- Run fetch for just one site:
```sh
poetry run …
```
=> Framework for running runners for sites

README.md
Added separate commands for Mac and changed `pyenv` to optional to make things simpler
=> Update setup steps in README.md for mac

.editorconfig
Pulled out @rajbot's changes to `.editorconfig` into its own PR so we can get it merged separately
=> Add editor config for markdown and text files

vaccine-feed-ingest/run.py
This looks for files named "fetch.*", and if there is only one and it is executable, then it runs it e.g. `fetch.sh` or `fetch.py`
This will allow use to support multiple languages for the runners.
=> Support multiple executable languages for runner

.github/workflows/lint.yml, .gitignore, poetry.lock, pyproject.toml, vaccine_feed_ingest/run.py, vaccine_feed_ingest/runners/us/vaccinespotter_org/fetch.sh, vaccine_feed_ingest/runners/us/vaccinespotter_org/normalize.sh, vaccine_feed_ingest/runners/us/vaccinespotter_org/parse.sh
`vaccine-feed-ingest all-stages` will run all stages for all sites and pass data around to each stage.
By default stores run data in local `out` directory, but allows specifying which directory to use with `--output-dir`
When a local directory is passes it used local file tools, when a gcs directrory is passed is uploads and downloads from gcs
=> Support full pipeline run!

vaccine_feed_ingest/runners/ca/sf_gov/README.md, vaccine_feed_ingest/runners/ca/sf_gov/fetch.sh, vaccine_feed_ingest/runners/ca/sf_gov/normalize.py, vaccine_feed_ingest/runners/ca/sf_gov/parse.py
Simple pipeline for SF.gov. This has most of the steps that were in your PR. It is most different in `normalize` stage because I am not using the jsonschema namedtuple.
We can add that back in a later PR.
=> Simple SF.gov pipeline example

vaccine_feed_ingest/ingestors/arcgis.py
Per [ArcGis's python documentation](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html#arcgis.features.FeatureLayer.query), setting `return_all_records = True` on a `query` causes:
> When True, the query operation will call the service until all records that satisfy the where_clause are returned.
It seems desirable to fetch all data - not just the first page - so add this parameter.
=> chore: return all records in ArcGIS fetch

vaccine_feed_ingest/ingestors/arcgis.py
Make "geojson" the default arcgis output format, but allow runners to configure it.
=> Support geojson output format, and make it configurable

vaccine_feed_ingest/run.py, vaccine_feed_ingest/runners/_shared/parse.py, vaccine_feed_ingest/runners/ak/arcgis/parse.yml, vaccine_feed_ingest/runners/al/arcgis/parse.yml, vaccine_feed_ingest/runners/az/arcgis/parse.yml, vaccine_feed_ingest/runners/in/arcgis/parse.yml, vaccine_feed_ingest/runners/md/arcgis/parse.yml, vaccine_feed_ingest/runners/mo/arcgis/parse.yml, vaccine_feed_ingest/runners/mt/arcgis/parse.yml, vaccine_feed_ingest/runners/pa/arcgis/parse.yml, vaccine_feed_ingest/runners/ri/arcgis/parse.yml, vaccine_feed_ingest/runners/sc/arcgis/parse.yml, vaccine_feed_ingest/runners/tx/arcgis/parse.yml
Similar to #26: ArcGIS feeds have a repeatable parse pattern, and we can
make it easy to parse new feeds by re-using a single runner.
Augment vaccine-feed-ingest to accept .yml configuration files if an
executable is not provided (for the parse stage), and use that config
to run a shared ArcGIS parser. This setup is designed so that the
vaccine-feed-ingest cli commands continue to operate as expected even
when a config file is found rather than an executable runner.
While ArcGIS is the only shared parser at the moment, this setup should
be able to support more shared parsers with minimal refactoring.
=> chore: shared parse.py with yml config for arcgis 

poetry.lock, pyproject.toml, vaccine_feed_ingest/run.py, vaccine_feed_ingest/runners/ak/arcgis/normalize.py, vaccine_feed_ingest/schema/schema.py
- chore: add normalized schema data types
Codify discussed target schema into classes with type hints, using
pydantic for runtime validation and serialization.
Future work can improve these types (e.g., enforcing ISO format for the
date and time fields rather than accepting arbitrary strings), but this
should be a sufficient starting point.
- chore: normalize ak/arcgis using data types
A sample normalization stage using the above types.
=> chore: add normalized schema

vaccine_feed_ingest/schema/schema.py
Per discussion offline, dropping `:ss` from schema for open hours.
=> chore: drop seconds from open hours schema

vaccine_feed_ingest/runners/ak/arcgis/normalize.py
#37 updated the schema to change the type of `Source.data`. Update `ak/arcgis` to properly set that field.
Additionally, add the arcgis id and layer id to the canonical id for a location, per discussion offline. The IDs now look like: `ak:arcgis:d92cbd6ff2524d7e92bef109f30cb366_0:0ed786e2-f009-4919-803a-8addbea8f9bd`.
=> fix: ak/arcgis normalizer ids and data

vaccine_feed_ingest/cli.py
If you add `OUTPUT_DIR=output_directory` to `.env` then commands will use that directory to output to.
This means you can setup an environment that all uses the same output directory and vial server without needing to pass the options each time.
=> Support specifying OUTPUT_DIR in .env file so you don't need to pass to all cmds

poetry.lock, pyproject.toml, vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/vial.py
Framework for matching source locations to existing locations when loading to VIAL. Followup PR will contain some matching logic in `def _match_source_to_existing_locations` method.
Process is for each source being loaded:
1. Stream existing locations to indexed geopandas dataframe
2. For each source location, attempt to match to existing location and decide if it definitely matchings or definitely is new.
3. Bulk load source locations to VIAL with matching info
4. Repeat for next source
Things I want to improve at a later date:
1. This will attempt to re-match each source location on each run even if it was already matched in a previous run. Instead it should filter out all of the source locations that are already matched somehow.
2. This will re-download the existing locations for each …
=> Framework for matching source locations to existing locations

README.md
We've moved most setup instructions to the wiki, so pointing there.
In a future PR we should probably remove the prod run and VIAL instructions since they are not relevant to most contributors.
=> docs(README): link to wiki for most setup

vaccine_feed_ingest/runners/ny/nyc_arcgis/parse.yml
Fixes #54 
Parse data from NYC's ArcGIS FeatureServer.
Presently the data contains ~600 rows, here are two samples:
```ndjson
{"attributes": {"ADA_Compliant": "Yes", "AdditionalInfo": "The physically accessible pathway to the entrance is on Irving Ave", "Address": "400 Irving Avenue", "Address2": "", "AgesServed": "", "AgesServed2": "", "AgesServed3": "", "AgesServed_Over18": "", "AgesServed_Under18": "", "AppointmentAvailability": "Available", "AvailabilityCount": null, "AvailabilityETLLastModified": 1619157370031, "AvailabilitySource": "NYC DoITT Salesforce", "AvailabilitySourceLastModified": null, "Borough": "Brooklyn", "ClosingHour_Friday": 2030, "ClosingHour_Monday": -1, "ClosingHour_Saturday": 1800, "ClosingHour_Sunday": 1900, "ClosingHour_Thursday": 2030, "ClosingHour_Tuesday": -1, …
```
=> parse nyc_arcgis

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/load.py
Add options to enable or disable matching when loading to vial
- `--match/--no-match` to enable/disable matching to existing locations with a default of `True`
- `--create/--no-create` to enable/disable creating new locations with a default of `False`
- `ENABLE_MATCH` to enable/disable matching to existing locations
- `ENABLE_CREATE` to enable/disable creating new locations
=> Option to enable and disable match/create when loading to vial

poetry.lock, pyproject.toml, vaccine_feed_ingest/stages/load.py
1. If there is a state specified then the state must match.
2. If there is a city specified then the city must have at least a `0.1` `jaro_winkler` similarity.
3. If there is a parent_organization/provider specified then the name must have at least a `0.1` `jaro_winkler` similarity.
4. There may not be any conflicting concordance links e.g. both have ride aid ids but the ids are different
=> FYI Add rules that preclude a match to vial

vaccine_feed_ingest/runners/ma/normalize.py, vaccine_feed_ingest/runners/ma/parse.py
Resolves #71.
This normalizes the data for MA.
As noted in the PR, most addresses follow the following format: `800 Boylston Street, Boston, MA 02199`
However, a number of them do not include "MA", and so there are some handlers to take care of that.
Additionally, a small patch to the parser to skip the first line as that includes the headers (which were causing bugs in normalization).
=> Add Normalizer for Mass.

vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/fetch.yml
GIScorps is a group of volunteers familiar with GIS systems that have been compiling a national dataset of testing (and later vaccination) locations for a few months already. Might be worth reaching out to them. Let me know and I can do an introduction with the person I've been in email contact with.
This data is likely to overlap quite a lot with existing data you may have and I'm sure they would also like to incorporate any new or modified data back into their own dataset for the various organizations that use that data. There are some details and links to their bulk-import spreadsheet and schemas at https://github.com/VacFind/GeoCompare/issues/7 and also in https://github.com/VacFind/GeoCompare/wiki/GISCorps-Output-Format
=> add fetch.yml for GISCorps national locations for vaccination sites

vaccine_feed_ingest/runners/wa/prepmod/fetch.py
Scrape the WA prepmod site html, continuing until there are no more pages and the request returns 302
I do not think an API exists, either officially or from poking around with adding `.json` to things so this is what we have to work with.
fixes #122
=> add WA fetch script

vaccine_feed_ingest/stages/site.py
When running any stages of the pipeline that are defined by `.yml` files, a warning about executability is presented:
```
04/24/2021 10:23:18 WARNING:ingest:parse.yml in /path/to/vaccine-feed-ingest/vaccine_feed_ingest/runners/wi/arcgis_map is not marked as executable.
```
it seems to me that yml files should not be executable (in fact things broke when I set my yml file to be executable). So this warning may cause needless confusion for people when a yml file passes through this function. In this PR I have added a check that tests for the presence of a yml file and passes it though as if it were not executable, but without generating a warning.
This check could also be moved inside the executable test to just silence the warning if that style is preferred.
=> prevent warning about executability from being generated for yml files

vaccine_feed_ingest/runners/az/arcgis/normalize.py
Partially adapted from the Alaska normalizer.
The main complexity is parsing site hours, which are in a very wide variety of time formats; it seems like a value is produced for almost all of them. I wasn't sure how deeply I should go into handling special cases versus keeping the normalizer simple; currently it's able to parse almost all of the times, but is fairly complicated and might not be robust. (Some sites have the hours listed for particular days as the string "BY APPOINTMENT ONLY" or "7:00 AM-5:00PM for second dose vaccine ONLY"; these are theoretically parseable, but it's not clear how they fit with the schema. The time parsing just falls back to `None` if it can't figure out what's going on.)
I checked for correctness by running `poetry run vaccine-feed-ingest normalize …
=> Normalize Arizona arcgis vaccine data (fixes #59)

vaccine_feed_ingest/runners/mt/arcgis/fetch.yml, vaccine_feed_ingest/runners/mt/arcgis/parse.yml, vaccine_feed_ingest/runners/tn/arcgis/fetch.yml, vaccine_feed_ingest/runners/tn/arcgis/parse.yml
per the linked issue, it seems like these two states do not offer vaccination site locations in their GIS data.
Per my comments in the individual issues for these states, this data may exist in the GISCorps dataset and can be submitted using the forms and spreadsheet templates available from the  GISCorps site (should be findable from here: https://covid-19-giscorps.hub.arcgis.com/)
fixes #158
=> remove TN and MT arcgis data sources

vaccine_feed_ingest/runners/nv/immunizenevada_org/parse.py
Fixes #92.
This PR takes the approach discussed in https://github.com/CAVaccineInventory/vaccine-feed-ingest/issues/92#issuecomment-826161377. It parses the HTML embedded in the fetched results from #91 and outputs JSON records.
Parsing HTML isn't the ideal approach, so if there's a better source of data, I'm more than happy to scrap this and replace it with a simpler parser.
If the `parse.py` output format looks OK, let me know, and I can start working on the normalization step (#93).
~I've included the commits from #91, since that hasn't been merged to main yet.~ PR #91 has been merged, so I've rebased against main.
=> Add nv/immunizenevada_org parser.

vaccine_feed_ingest/runners/ak/arcgis/normalize.py, vaccine_feed_ingest/runners/az/arcgis/normalize.py, vaccine_feed_ingest/runners/ny/am_i_eligible_covid19vaccine_gov/normalize.py
With the [vaccine type enum](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Normalized-Location-Schema#vaccine-type-enum) now specified, fix existing normalizers to use values from the enum.
We will need to fix this again as PRs get merged in the coming days, but in the meantime let's get the files used as examples showing the new values!
=> fix: normalized vaccine types

vaccine_feed_ingest/runners/_shared/parse.py
Allows the parser to work even when the location list is not top-level JSON. For example, if the JSON file contains `[{"locations":[...actual list of locations...]}]`, the following parse.yml file would work:
```yaml
---
state: ...
site: ...
parser: json_list
path: [0, "locations"]
```
This will be useful for the il/juvare parser. If this is merged, the [wiki page](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/JSON-to-NDJSON-Parser) should also be updated.
=> Add path support to the shared json_list parser

vaccine_feed_ingest/runners/il/juvare/README.md, vaccine_feed_ingest/runners/il/juvare/fetch.sh
Scrapes the Illinois Department of Public Health vaccine appointment form at <https://covidvaccination.dph.illinois.gov/>. This form lists sites with available appointments, using [Juvare](https://www.juvare.com).
NOTE: it may be possible to scrape additional information, like phone numbers, by following the link for each site. Example: <https://archive.md/CRuvx>.
Fixes #150.
=> Add IL juvare fetcher

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/common.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/stages/outputs.py
Validate the outputs of parse and normalize stages to ensure they match the spec.
Does not upload them if they failed.
This can be turned off with `--no-validate` or `ENABLE_VALIDATE=false`
=> Validate stage outputs with the option to turn off

vaccine_feed_ingest/vial.py
There is a max size for POSTs of `32MB` so we need to batch imports. I picked batching of `1,000` records because it is low enough that it will be well under `32MB` and high enough that many feeds will only have one batch.
=> FYI Import source locations to VIAL in batches of 1k

.github/pull_request_template.md
Currently there is a config issue where `isort` locally adds newlines which are rejected by `isort` in SuperLinter (#208).
For now, prompt contributors to run the auto-formatters only on the `runners` dir to avoid this issue for most contributions.
=> docs(pr): suggest autoformatting runners dir only

.github/pull_request_template.md, tox.ini
Add a tox command that fixes lint errors instead of failing:
```
poetry run tox -e lint-fix
```
This command should be used locally, but not for an automation.
=> Add a tox lint-fix command

vaccine_feed_ingest/runners/ca/metrolink/parse.py
|-|
| Resolves #178 |
State: ca |
Site: metrolink |
uses bs4 to parse table. raw file includes only site name, address, metrolink line, metrolink station.
```json
{"site_name": "Pomona Fairplex (Gate 15)", "site_address": "2352 Arrow Hwy., Pomona", "metrolink_line": "San Bernardino", "metrolink_station": "Pomona - North"}
{"site_name": "Cal State Northridge", "site_address": "18343 Plummer Street, Northridge", "metrolink_line": "Ventura County", "metrolink_station": "Northridge"}
{"site_name": "El Sereno Recreation Center", "site_address": "4721 Klamath St., Los Angeles", "metrolink_line": "San Bernardino", "metrolink_station": "Cal State L.A."}
{"site_name": "St. John's Well Child and Family-Lincoln", "site_address": "2515 Alta St., Los Angeles", "metrolink_line": "Union …
```
=> Ca metrolink parse

vaccine_feed_ingest/runners/ca/sf_gov/normalize.py, vaccine_feed_ingest/schema/schema.py
1. Change wheelchair to be an enum of `yes`, `partial`, `no`
2. Fix `walk` and `drive` to be bool like in the spec.
Change `sf_gov` to produce wheelchair enum values. It is the only one using the schema right now.
=> Fix Access schema with wheelchair enum

.github/ISSUE_TEMPLATE/runner-normalize.md, poetry.lock, pyproject.toml, vaccine_feed_ingest/runners/ak/arcgis/normalize.py, vaccine_feed_ingest/runners/az/arcgis/normalize.py, vaccine_feed_ingest/runners/mo/arcgis/normalize.py, vaccine_feed_ingest/runners/pa/arcgis/normalize.py, vaccine_feed_ingest/runners/ri/arcgis/normalize.py, vaccine_feed_ingest/runners/sc/arcgis/normalize.py, vaccine_feed_ingest/schema/schema.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/utils/match.py, vaccine_feed_ingest/vial.py
[`vaccine-feed-ingest-schema` `v0.1.0`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/releases/tag/0.1) is a published version of the normalized schema from this repo.
Switch all present uses of the local schema to the published schema, and add a deprecation warning on use of the local schema.
I will also update [the `Normalized Location Schema` wiki page](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Normalized-Location-Schema) to referenced the published package rather than the local file.
=> refactor: use external schema

vaccine_feed_ingest/runners/nv/immunizenevada_org/normalize.py, vaccine_feed_ingest/runners/nv/immunizenevada_org/parse.py
Fixes #93 
Two questions:
1. There wasn't a natural ID in the fetched data, so I used the name of the location. My IDs look like this: `immunizenevada_org:Albertsons #1059`. Is this acceptable?
2. For the `fetched_from_uri` value I used the URL for the NV vaccine locator: `https://www.immunizenevada.org/covid-19-vaccine-locator`. That's not strictly accurate, since the data was actually fetched by POSTing to `https://www.immunizenevada.org/views/ajax`, but if you GET that url, you get a `404`. That seems less helpful, despite being technically accurate. Thoughts?
=> Add normalizer for nv/immunizenevada_org.

vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/validation.py
Supplement existing validation that runs after the `normalize` step to confirm that `latitude` and `longitude` values make sense. This is primarily targeted at catching (and blocking) normalizers which flip lat/lng.
The configuration for the bounding box is a best-guess based on current config for VaccinateTheStates.com.
=> chore: validate in-bound latitude and longitude

vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py, vaccine_feed_ingest/runners/us/vaccinespotter_org/normalize.py
* Fix a boolean logic bug introduced in #238. This ultimately doesn't impact the output (because under the existing logic flipped lat/lngs still failed the method), but we should fix it!
* Update `vaccinespotter_org` to begin to use the schema in order to enforce:
* valid addresses
* valid lat/lngs 
We should finish converting `vaccinespotter_org` to use the schema (#233), but validation errors on `Address` and `Location` were preventing promotion of this data, so I did this partial fix.
=> fix(vaccinespotter_org): valid addresses and lat/lngs

vaccine_feed_ingest/stages/load.py
Do not use concordances to filter out match candidates.
1. The concordance values are not unique ids so it is possible to have multiple ids per authority
2. The concordance values do not have a standard format so it is possibel to have 08088 and 8088
=> Do not use concordances to filter out match candidates

vaccine_feed_ingest/cli.py
|-|
| Resolves #210 |
State:  |
Site:  |
A straightforward fix to how `fetch` and `parse` statuses are computed for arcgis based sources, as seen when running the following command:
```
poetry run vaccine-feed-ingest available-sites
```
Before this fix, the output for arcgis sites looked like this:
```
ak/arcgis no-fetch no-parse normalize
```
(even though Alaska has valid fetch and parse yml files). After this fix, the output looks correct:
```
ak/arcgis fetch parse normalize
```
I also verified that none of the output changes for non-arcgis sites.
=> Issue #210: fix fetch and parse computation for arcgis sites

vaccine_feed_ingest/runners/ma/vaxfinder_gov/normalize.py
|-|
| Resolves #223 |
State: ma |
Site: vaxfinder_gov |
Pretty straightforward bug fix:
1. Use the Pydantic schema as noted in #233
2. Since there's no ID in the raw data, generate one via an md5 hash of the name & address
```json
{"id": "ca79bf5dd35fb01154dab979d1ac103f", "name": "CVS (Centre Ave.)", "address": {"street1": "385 Centre Ave", "street2": null, "city": "Abington", "state": "MA", "zip": "02351"}, "location": null, "contact": [{"contact_type": "booking", "phone": null, "website": "https://vaxfinder.mass.gov", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": …
```
=> Fix normalized records for vaxfinder, and use Pydantic schema

.github/workflows/lint.yml
Run `poetry run tox` on PR. This will:
* Run `pytest` and enforce that any written tests pass.
* Run python related linters with the same config as they use locally. We do this (rather than using SuperLinter) to work around an ongoing issue where SuperLinter appears to be using a different `isort` configuration than it should be.
Because python linters are run via `tox`, disable them in SuperLinter.
Note: `tox` is slow on first-run, and in CI it will always be first-run. Future work may include adding appropriate cacheing for the dependencies brought in by tox (though this will weaken tox's value slightly, the speedup may be needed).
⚠️ In order to not break open PRs which do not include this updated workflow, we will _not_ require the `Python Lint & Test` check for several days. In the …
=> ci: add tox to lint job

.github/workflows/lint.yml
Update `poetry install` in CI to go from `--dev-only` to `--extras lint`. This significantly increases the packages installed, but will work around a current issue where the `--dev-only` flag is not found.
Given our cacheing strategy, we will _rarely_ install all packages, so this is an acceptable fix to leave in place for a while.
=> fix: poetry install --extras lint

poetry.lock, pyproject.toml, vaccine_feed_ingest/runners/ak/arcgis/normalize.py, vaccine_feed_ingest/runners/az/arcgis/normalize.py, vaccine_feed_ingest/runners/ca/sf_gov/normalize.py, vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py, vaccine_feed_ingest/runners/in/arcgis/normalize.py, vaccine_feed_ingest/runners/ky/govstatus/normalize.py, vaccine_feed_ingest/runners/ma/vaxfinder_gov/normalize.py, vaccine_feed_ingest/runners/me/maine_gov/normalize.py, vaccine_feed_ingest/runners/mo/arcgis/normalize.py, vaccine_feed_ingest/runners/nc/myspot_gov/normalize.py, vaccine_feed_ingest/runners/nv/immunizenevada_org/normalize.py, vaccine_feed_ingest/runners/ny/am_i_eligible_covid19vaccine_gov/normalize.py, vaccine_feed_ingest/runners/ok/vaccinate_gov/normalize.py, vaccine_feed_ingest/runners/pa/arcgis/normalize.py, vaccine_feed_ingest/runners/ri/arcgis/normalize.py, vaccine_feed_ingest/runners/sc/arcgis/normalize.py, vaccine_feed_ingest/runners/us/vaccinespotter_org/normalize.py, vaccine_feed_ingest/runners/wa/prepmod/normalize.py, vaccine_feed_ingest/schema/schema.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/utils/match.py, vaccine_feed_ingest/vial.py
Update `vaccine_feed_ingest_schema` to `v0.2.1` ([release notes](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/releases/tag/0.2.1)).
After the update, migrate all users of the existing `schema` shared import to import either `load` or `location` (per the release notes).
Finally, migrate additional users of the deprecated in-source `schema` to the published one.
=> chore(deps): bump vaccine_feed_ingest_schema to v0.2.1

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/load.py
The default distance is to collect existing locations within .6 degrees (66.6 km, 41 mi) as potential matching candidates. If there are no candidates then it will create as new.
We can adjust this threshold lower to create more locations, but also potentially create more duplicates.
=> Add option to change candidate distance when loading to vial

vaccine_feed_ingest/runners/ak/arcgis/normalize.py, vaccine_feed_ingest/runners/az/arcgis/normalize.py, vaccine_feed_ingest/runners/in/arcgis/normalize.py, vaccine_feed_ingest/runners/mo/arcgis/normalize.py, vaccine_feed_ingest/runners/pa/arcgis/normalize.py, vaccine_feed_ingest/runners/ri/arcgis/normalize.py, vaccine_feed_ingest/runners/sc/arcgis/normalize.py
Source IDs had a prefix of `{state}:arcgis` so the source should match that.
=> Change arcgis source to match arcgis ids

vaccine_feed_ingest/runners/az/arcgis/normalize.py
Downstream systems are currently receiving `az`, `AZ`, and `Arizona`. Hardcode to `AZ`.
=> fix: hardcode arizona to AZ

vaccine_feed_ingest/runners/ca/los_angeles_gov/fetch.sh
|-|
| Resolves #269 |
State: ca |
Site: los_angeles_gov |
* none
```
var unfiltered = [
{
"id": 25,
"xParent": 15,
"NumChildren": 0,
"inactive": "",
"organization": "Reported",
"name": "Crenshaw Clinic",
"addr1": "1261 W 79th Street",
"addr2": "Los Angeles, CA 90044",
"vaccines": "m",
"logo": "",
"lat-lon": "33.96669248204296,-118.29743217895289",
"lat": 33.96669248204296,
"lon": -118.29743217895289,
"mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.96669248204296%2C-118.29743217895289&z=16",
"notes": "Run by LA City Fire Dept.",
"notesSpn": "Dirigido por Departamento de Bomberos de la ciudad de Los Ángeles",
"alt": "Tues-Sat 8am-4pm",
"altSpn": "martes-sábado 8am-4pm",
"date": "",
"time": "",
"link": …
```
=> add ca/los_angeles_gov/fetch.sh

vaccine_feed_ingest/runners/ca/sf_gov/normalize.py, vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py, vaccine_feed_ingest/runners/ny/am_i_eligible_covid19vaccine_gov/normalize.py, vaccine_feed_ingest/runners/us/vaccinespotter_org/normalize.py
|-|
| Related #233 |
Used the Pydantic schema for the following:
- ca/sf_gov
- ct/covidvaccinefinder_gov
- us/vaccinespotter_org
- ny/am_i_eligible_covid19vaccine_gov
Additionally, when updating `us/vaccinespotter_org`, we could be using `site["provider_brand_name"]` and `site["provider_brand_id"]` to populate the links & parent_org. There were a few edge cases I didn't want to tackle, but figured I should call it out here.
=> Use schema in earlier normalizers

.github/workflows/lint.yml
Add a CI job which:
* runs `poetry run vaccine-feed-ingest --help` after performing environment setup. This will prevent PRs from merging which fundamentally break the CLI (e.g., invalid imports, etc.)
* if a runner was modified (other than `us/*`), run `all-stages` for that runner! This will prevent runners which do not run from being merged (outside of the `us/` directory)
⚠️ After this is merged, CI jobs will interact with external sites to perform the `fetch` stage. If additional large sites are brought into the pipeline outside of the `us/*` directory, we may need to add exemptions for them also.
🔗 [Here is a sample CI run of a PR which modified runners](https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/286/checks?check_run_id=2464296658). In that PR I modified the …
=> ci: run modified runners except for us/*

.github/workflows/lint.yml
This job targets modified runners in the context of a PR. It does not make sense to run it outside that context, because too many runners will be selected.
Additionally, use `-s` rather than `-f` to attempt to enforce that the instruction file is non-empty.
=> ci(runner): skip running runners outside of prs

.github/workflows/lint.yml
As shared in #278, we plan to release `v1.0.0` of the schema. When it is released, all open PRs will need to be updated to include it properly.
Once the PR bumping the schema is merged, merge this PR and require it as a PR check.
* Old branches will fail the required check (because it is not defined)
* New branches will pass the required check (because it simply echos a value)
=> ci: force rebase job

vaccine_feed_ingest/runners/ca/sf_gov/normalize.py
Fixed ca/sf_gov normalizer:
1. Skipping string "None" values
2. Encoding contacts as one entry per value
=> Fix ca/sf_gov normalize after validation landed

.gitignore, tests/utils/test_provider_id_from_name.py
|-|
| Addresses #254  |
State:  |
Site:  |
This PR introduces tests for the `provider_id_from_name()` method. This is in preparation to enhance this method to recognize additional providers. Any time regexes are involved, tests are a good idea.
This is a test-only change, so this section doesn't apply. But here's the result of running the test command:
```
> poetry run tox -q -e test
======================================================================================================== test session starts =========================================================================================================
platform darwin -- Python 3.9.4, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
cachedir: .tox/test/.pytest_cache
rootdir: /Users/shashankr/projects/vaccine-feed-ingest …
```
=> Test for provider_id_from_name()

vaccine_feed_ingest/runners/il/juvare/normalize.py
|-|
| Resolves #205 |
State: il |
Site: juvare |
Several things about this normalizer need discussion:
- It's possible to generate direct links to the sign-up form for each site, like this: <https://events.juvare.com/IL-IDPH/0406ec6d-e7c9-40f0-aa86-98b0d8a5acdf/>. However, these links bypass the consent form at <https://covidvaccination.dph.illinois.gov/>, so I thought it would be safer to return that site instead.
- The source only seems to list sites that have available signup times. I'm therefore returning `"supply_level":"in_stock"`, on the assumption that any site with available times will have available stock.
- The source frequently includes duplicates of the same site with different dates or different vaccine types (1st dose vs. 2nd dose). I'm returning the …
=> normalize juvare for il

setup.sh
A lower friction setup helps more folks to contribute.
I tested this in an Ubuntu container with `sudo` temporary removed from the `setup.sh` script.
test Dockerfile:
```Dockerfile
FROM ubuntu
RUN apt-get update && \
apt-get upgrade -y && \
apt-get install -y \
git
WORKDIR /code/
RUN git clone https://github.com/CAVaccineInventory/vaccine-feed-ingest.git
WORKDIR /code/vaccine-feed-ingest
COPY setup.sh ./
```
Temporary patch to remove sudo so it will run in a container
```diff
--- a/setup.sh
+++ b/setup.sh
@@ -63,7 +63,7 @@ setup_linux() {
echo "I'm about to use sudo to install some libraries, python 3.9, and curl"
echo "so will ask for your root password"
echo ""
-    sudo apt-get install \
+    apt-get install \
libbz2-dev \
liblzma-dev \
libreadline-dev \
```
Tested with 
```sh
docker …
```
=> setup.sh for linux

tests/utils/test_location_id_from_name.py
This is a follow-up to https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/289 where the `location_id_from_name` function was added.
=> Add tests for location_id_from_name

vaccine_feed_ingest/runners/az/pinal_ph_clinics_gov/parse.py
This addresses some PR feedback from https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/307
```
poetry run vaccine-feed-ingest fetch --state az
poetry run vaccine-feed-ingest parse --state az
```
=> [az/pinal_ph_clinics_gove] Clarify input/output

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/common.py, vaccine_feed_ingest/stages/enrichment.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/load.py
Add a bare bones `enrich` stage that processes the normalized records from ingestors and prepares them for load.
```
vaccine-feed-ingest enrich ca/sf_gov
```
Right now this stage copies all locations that pass validation, but in the future it will:
1. Ensure a full address for all locations (street, city, state, zip) if possible
2. Ensure lat-lng exists using a geocoder
3. Fill out parent_organization based on name
4. Fill out concordances from parent_organization, source, and name
5. Match to external concordances like google places, OSM POI, or Placekey (if api pricing and limits allow)
=> Add enrich stage between normalize and load

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/common.py, vaccine_feed_ingest/stages/load.py
Add pipeline command to cli that can run all stages from fetch to load, and allows you to customize which stages to run.
Run just normalize:
```
vaccine-feed-ingest pipeline ca/sf_gov --stages=normalize
```
Run ingestion part:
```
vaccine-feed-ingest pipeline ca/sf_gov --stages=fetch,parse,normalize
```
Run load part:
```
vaccine-feed-ingest pipeline ca/sf_gov --stages=enrich,load-to-vial
```
=> Add pipeline command to cli that runs all stages from fetch to load

vaccine_feed_ingest/runners/ny/northwell_health/fetch.py
|-|
| Resolves #317 |
State: ny |
Site: northwell_health |
After some digging, I managed to find an API! 😄 
The vaccine locations are paginated. For n pages, n+1 requests are made.
1. GET "https://api.northwell.edu/v2/vax-locations/all" to grab page urls
2. GET "https://api.northwell.edu/v2/vax-locations/all?page=1
&nbsp;&nbsp;&nbsp;n. GET "https://api.northwell.edu/v2/vax-locations/all?page={n}"
```json
[
{
"id": 13,
"name": "Westchester - Chappaqua Crossing (480 N Bedford Rd) -- Moderna",
"address": "480 N Bedford Rod",
"suite": "",
"city": "Chappaqua",
"state": "New York",
"zip": "10514",
"county": "Westchester",
"latitude": "41.1789",
"longitude": "-73.7515",
"program_url": "https://northwellvaccine.force.com/s/?id=a1T4x000007TWHNEA4",
"vaccine_manufacturer": …
```
=> Added fetch ny/northwell_health

vaccine_feed_ingest/runners/ca/metrolink/normalize.py
|-|
| Resolves #179 |
State: ca |
Site: metrolink |
* very minimal data at this site, so we do the best we can.
```json
{"id": "ca:metrolink:Pomona Fairplex (Gate 15):Pomona", "name": "Pomona Fairplex (Gate 15)", "address": {"street1": "2352 Arrow Hwy.", "street2": null, "city": "Pomona", "state": "CA", "zip": "0"}, "location": null, "contact": null, "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": ["metrolink_line__ca_specific:San Bernardino", "metrolink_station__ca_specific:Pomona - North"], "active": null, "source": {"source": "ca:metrolink", "id": "Pomona Fairplex (Gate 15):Pomona", "fetched_from_uri": …
```
=> Ca metrolink normalize

vaccine_feed_ingest/runners/in/arcgis/normalize.py
|-|
| Resolves #231 |
State: in |
Site: arcgis |
* It's easy enough to pull zip and state off the end, and then we get to this point:
```{python}
#
#
```
```json
{"id": "in:arcgis:46630b2520ce44a68a9f42f8343d3518_0:cbdadf08-4e7d-4946-b730-bc5db81cae77", "name": "Adams Memorial Hospital", "address": {"street1": "1100 Mercer Ave", "street2": "Decatur", "city": "Decatur", "state": "IN", "zip": "46733"}, "location": {"latitude": 40.81772566014207, "longitude": -84.91267832291557}, "contact": [{"contact_type": null, "phone": null, "website": "https://vaccine.coronavirus.in.gov", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": [{"vaccine": "moderna", "supply_level": null}], "access": null, …
```
=> expand address parsing for in/arcgis

vaccine_feed_ingest/runners/ak/arcgis/normalize.py, vaccine_feed_ingest/runners/ky/govstatus/normalize.py, vaccine_feed_ingest/runners/ma/vaxfinder_gov/normalize.py, vaccine_feed_ingest/runners/sc/arcgis/normalize.py, vaccine_feed_ingest/utils/normalize.py
Fix schema validation errors for `ma/vaxfinder` and `ak/arcgis`.
=> Fix ma/vaxfinder and ak/arcgis normalizers.

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/load.py
Provide an option with calling `load-to-vial` to manually match or create.
```
vaccine-feed-ingest load-to-vial ca/sf_gov --match-ids=sf_gov:ocean_park=recKQrT7tv5yoC5r2,sf_gov:safeway_pharmacy_2646=rechVtcpquzPs8Vfg
```
```
vaccine-feed-ingest load-to-vial ca/sf_gov --create-ids=sf_gov:ocean_park,sf_gov:safeway_pharmacy_2646
```
=> Option to override match and create ids when loading

tests/utils/test_provider_id_from_name.py, vaccine_feed_ingest/runners/wa/prepmod/normalize.py, vaccine_feed_ingest/runners/wa/prepmod/parse.py
Resolves #345
Fix validation errors in the wa/prepmod noramlizer. It also required some changes in the parser to get some more reliable IDs.
=> normalize: fix validation errors in wa/prepmod (#345).

poetry.lock, pyproject.toml, vaccine_feed_ingest/runners/ri/arcgis/normalize.py, vaccine_feed_ingest/utils/normalize.py
Fix validation errors for ri/arcgis. I also introduced a URL normalizer (in this case, to add the scheme to the URL).
=> normalize: fix validation errors for ri/arcgis (#344).

vaccine_feed_ingest/runners/nc/myspot_gov/normalize.py
The phone numbers and websites were extremely messy, so I tried to capture what I could with regular expressions.
=> normalize: fix validation errors in normalize for nc/myspot_gov (#339).

tests/conftest.py, tests/stages/test_enrichment.py, vaccine_feed_ingest/stages/enrichment.py
In the enrichment stage, add the provider from `normalize.provider_id_from_name` as a link if it is missing. It will not overwrite values if they were added in the normalize step.
This means we don't have to add it in all of the normalize stages if we don't want to.
=> Enrich locations with provider info from name

vaccine_feed_ingest/utils/normalize.py
Turn provider regexs into constants and group them by provider. 
This was introduced in #360 and I wanted to get that improvement in without while we discuss the merits of umbrella org vs. brand.
=> Turn provider regexs into constants and group them by provider. 

vaccine_feed_ingest/stages/enrichment.py
Ensure that we are sending locations to VIAL that are usable.
VIAL needs a state, zipcode, and lat-lng.
This PR does not attempt to add missing fields, just do the validation.
I can add the fixing in a later PR.
=> Skip locations missing street, city, state, zipcode, or Lat-Lng

tests/utils/test_provider_id_from_name.py, vaccine_feed_ingest/utils/normalize.py
|-|
| Resolves: #254 |
State: |
Site: |
Continuation of work started with #332. This PR builds on https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/pull/21 to add support of extraction of more vaccine providers.
This PR also refactors the provider_id code to make it easier to maintain and extend by extract config out of code.
I will run the runners shortly ...
=> Support extraction of ids for more providers (L - Z) found in data

tox.ini, vaccine_feed_ingest/runners/dc/district/parse.py
|-|
| Resolves #401 |
State: DC |
Site: district |
I also updated tox.ini so `tox -e lint-fix` so that flake8 runs _after_ black et al. have cleaned up the code for us.  Otherwise, flake8 blows up on things that black/isort would have fixed anyway.
```json
{"Walk-Up Site": "Arena Stage", "Address": "1101 6th St SW", "Normal Days / Hours": "Thursday-Sunday \n8am-12pm, 1pm-5pm", "Vaccine": "Pfizer", "May 1 Walk-Up": "Pfizer \n8am-12pm and 1pm-5pm"}
{"Walk-Up Site": "Entertainment and Sports Arena", "Address": "1100 Oak St SE", "Normal Days / Hours": "Switching to RISE after May 1", "Vaccine": "Pfizer", "May 1 Walk-Up": "Pfizer \n9am-5pm"}
{"Walk-Up Site": "Fort Stanton Rec Center", "Address": "1812 Erie St, SE", "Normal Days / Hours": "May 3-May 6 and May 10-May13 \n9am-1pm …
```
=> add parser for dc/district

vaccine_feed_ingest/ingestors/arcgis_ingest.py, vaccine_feed_ingest/runners/md/arcgis/fetch.yml, vaccine_feed_ingest/runners/md/arcgis/normalize.py
|-|
| Resolves #56 |
State: MD |
Site: arcgis |
Updates `ingestors.fetch_geojson()` to insert `layer_id` and `service_item_id` in each site record, per discussion in the issue.
Still need to clean up the phone numbers to pass the new validation before this is ready to merge, but wanted to get something up for folks to look at.
```json
{"id": "md_arcgis:d677f143334648a1a40b84d94df8e134_4_84", "name": "Luminis Health Anne Arundel Medical Center", "address": {"street1": "2001 Medical Parkway,", "street2": null, "city": "Annapolis", "state": "MD", "zip": "21401"}, "location": {"latitude": 38.990512076102036, "longitude": -76.5341664410021}, "contact": [{"contact_type": null, "phone": null, "website": "https://luminis.health/community-vaccine", "email": null, "other": null}, …
```
=> Normalize ArcGIS for MD

vaccine_feed_ingest/runners/ct/covidvaccinefinder_gov/normalize.py
Linking on networkId is causing locations in the same network (e.g., Walgreens) to match with each other when they should not. Remove the link.
=> chore: remove networkId as link in ct

vaccine_feed_ingest/runners/az/arcgis/normalize.py
Fix time normalization for AZ arcgis.
|-|
| Resolves #357 |
State: AZ |
Site: arcgis |
- [ * ] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ * ] I ran auto-formatting: `poetry run tox -e lint-fix`
=> fix time normalization for az/arcgis

vaccine_feed_ingest/runners/nj/vaccinate_nj/fetch.py
|-|
| Resolves #555  |
State: NJ |
Site: Vaccinate NJ |
The data is currently displayed at vaccinatenj.com/availability using an iframe in the HTML, but the Datatable itself which acts as a frontend to the database is at https://c19vaccinelocatornj.info instead, hence the url.
```json
{"data": [{"name": "Rite Aid #10454", "id": "a330a478-6171-47dc-8b5b-fcbd73b9f298", "city": "Moorestown", "zipCode": "08057", "county": "Burlington", "url": "https://www.riteaid.com/pharmacy/covid-qualifier", "type": "Pharmacy", "availabilityStatus": "Available", "availabilityChangedDate": "2021-04-29T15:47:46Z", "address": "121 West Main Street", "phone": "(800) 748-3243", "createdDate": "2021-03-28T00:43:43Z", "updatedDate": "2021-05-06T00:16:07Z", "scheduling": ["Online"], …
```
=> Fetch Vaccinate NJ for NJ

vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/vial.py
When `POST`ing large sites (e.g., `us/vaccinespotter_org`, `us/vaccinefinder_org`, etc.) to VIAL, we page the POST calls.
Unfortunately, we were returning after the first page. Fix this so that we attempt multiple pages.
Naively, we fail on the first error encountered. If this proves to be an issue we can implement retry logic.
=> fix(import_source_locations): allow multiple pages

vaccine_feed_ingest/runners/ak/clinic_list/parse.yml
|-|
| Resolves #497  |
State: AK |
Site: clinic_list |
For some reason, they're using `flu_vaccinations` etc. to represent COVID vaccinations data. Sigh.
```json
{"attributes": {"CreationDate": 1608936294888, "Creator": "", "EditDate": 1617228680475, "Editor": "kelly.isham_Alaska_DHSS", "address": "579 Kongosak St", "adminContactName": "Andrey Boskhomdzhiev\nNSB PHN Program Coordinator \n907-852-0270\nandrey.boskhomdzhiev@north-slope.org\n", "adminEmail": "andrey.boskhomdzhiev@north-slope.org", "city": "Barrow", "cost_other": null, "datesubmited": 1608930000000, "flu_acceptsInsurance": "yes_please_contact_your_insuran", "flu_cost": "no_cost", "flu_vaccinations": "pfizer", "flu_walkins": "no_please_make_an_appointment", "globalid": "85b07ac7-c9b6-4d09-83ec-a720998c2fbf", …
```
=> Parse clinic_list for AK

tests/conftest.py, tests/utils/test_provider_id_from_name.py, tox.ini, vaccine_feed_ingest/stages/load.py
1. Improve logs for the matcher so we know what is matching
2. Fix tox to also run in the `tests` directory
```
MISSING: sf_gov:cvs_store_10080 (CVS Store #10080) has no matching candidates
AMBIGUOUS: sf_gov:walgreens_10044 (Walgreens #10044) has 2 matches e.g. recj2Z2zCg9AaUFUl (Walgreens #10044), recagMTxOGRpY9PEy (Sutter Health-SF Castro St)
MATCH: sf_gov:walgreens_1054 (Walgreens #1054) matched to recvLheXFzUrA8EN6 (WALGREENS #1054)
```
```
Imported 94 source locations for sf_gov (0 new, 67 matched, 27 unknown)
```
=> Improve logs for the matcher so we know what is matching

poetry.lock, pyproject.toml, tests/conftest.py, tests/utils/test_match.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/utils/match.py, vaccine_feed_ingest/utils/normalize.py, vaccine_feed_ingest/utils/parse.py
1. Move address similarity to helper, and allow for slight differences for a match to count.
2. If providers are available then block matching if providers are dissimilar
3.  If phone numbers are available then block matching if phone numbers are dissimilar
This does not include the promised address matching improvements because I am still figuring out how to make them work on dirty addresses.
=> Improve matcher to look at phone numbers and providers

vaccine_feed_ingest/runners/fl/state/fetch.sh
|-|
| Resolves #376|
State: fl |
Site: floridahealthcovid19.gov |
The data is json embedded in the html page.  Attached one line of sample.
```json
{"id":"34416","title":"Southern Internal Medicine","address":"404 NW Hall of Fame Dr","source":"manual","content":"","location":{"icon":"https:\/\/floridahealthcovid19.gov\/wp-content\/plugins\/wp-google-map-gold\/assets\/images\/default_marker.png","lat":"30.18410951353843","lng":"-82.69534913079957","city":"Lake City","state":"FL","country":"United States","onclick_action":"marker","redirect_custom_link":"","marker_image":"\/wp-content\/themes\/wordpress-template\/assets\/images\/pin_orange.png","open_new_tab":"yes","postal_code":"32055","draggable":false,"infowindow_default_open":false,"animation":"","infowindow_disable":true …
```
=> Fetch floridahealthcovid19.gov for FL

tests/conftest.py, tests/utils/test_match.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/utils/match.py
1. Skips tag concordances: those that start with _
2. Skips matching conflicting concordances like locations with different google places ids
This is the prerequisite to adding "provider tags" to concordances
=> Improve concordance matching mainly by skipping those with underscores

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/vial.py
Load source locations from VIAL and skips matching locations that have already been matched.
The source locations will be updated with the latest data just not with any matching information.
=> Skip matching source locations that are already matched

vaccine_feed_ingest/runners/ct/state/fetch.py
|-|
| Resolves #478 |
State: CT |
Site: state |
```json
{
"results": [
{
"number": 72490171,
"name": "Stoll's Pharmacy, Inc. COVID-19 Vaccine Clinic",
```
- [ ✅ ] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ ✅ ] I ran auto-formatting: `poetry run tox -e lint-fix`
=> add fetch for ct/state

tests/stages/test_enrichment.py, vaccine_feed_ingest/stages/enrichment.py
If `phonenumbers` can parse the phone number, then normalize it to the "national" format `(###) ###-#### ext. #####`.
If it cannot parse it then leave it as-is.
=> Normalize phone number format if possible to (###) ###-#### ext. #####

vaccine_feed_ingest/utils/match.py
Location data in VIAL has legacy concordance fields that have 't fully been copied over to concordances. Use these fields when matching
- google_places_id field -> google_places concordance
- vaccinefinder_location_id -> vaccinefinder_org concordance
- vaccinespotter_location_id -> vaccinespotter_org concordance
=> Handle legacy concordances stored as fields on location

vaccine_feed_ingest/runners/wa/state/fetch.py
|-|
| Resolves #479 |
State: WA |
Site: state |
Very convenient graphql API with self documented interface. Seemed fine to grab it all in one page. About 2k results when I tested it out.
```json
{"data":{"searchLocations":{"paging":{"total":1921,"pageNum":1,"pageSize":1000000},"locations":[{"locationId":"recT5VYLb0qwyVTSz","locationName":"North Basin - Davenport","locationType":null,"providerId":null,"providerName":null,"departmentId":null,"departmentName":null,"addressLine1":"100 3rd Street","addressLine2":null,"city":"Davenport","state":"Washington","county":"Lincoln","zipcode":"99122","latitude":47.65713,"longitude":-118.14546,"description":null,"contactFirstName":null,"contactLastName":null,"fax":null,"phone":"(509) …
```
=> Add fetch step for wa/state. Fixes #479

tests/utils/test_match.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/utils/match.py
I am trying to handle the case were these two confirmed **different** clinics have the same address, but a different phone number:
1. "The Little Clinic": https://vial-staging.calltheshots.us/admin/core/location/19179/change/
2. "Kroger": https://vial-staging.calltheshots.us/admin/core/location/18821/change/
Previously I skipped matching if phone numbers differed, but it is common for locations to have a 800 number and a location number and for different feeds to use different ones.
This relaxes the exclusion rule to only compare phone numbers with the same area code. This should hopefully still skip  merging "The Little Clinics" while still getting locations with different numbers in each feed.
=> Relax phone number exclusion to only mismatch by area code

vaccine_feed_ingest/runners/sd/arcgis/normalize.py
|-|
| Resolves #526  |
State: SD |
Site: arcgis |
```json
{"id": "sd_arcgis:3bb3f167d57149ef8027a68a609edc2d_0_4dd5c027-89c2-4644-91fa-e48245a109c3", "name": "WALMART PHARMACY #3853", "address": {"street1": "2791 DAKOTA AVE S", "street2": null, "city": "HURON", "state": "SD", "zip": null}, "location": {"latitude": 44.33447799999999, "longitude": -98.214367}, "contact": [{"contact_type": null, "phone": null, "website": "https://www.walmart.com/cp/1228302", "email": null, "other": null}], "languages": null, "opening_dates": null, "opening_hours": null, "availability": null, "inventory": null, "access": null, "parent_organization": null, "links": null, "notes": null, "active": null, "source": {"source": "sd_arcgis", "id": "4dd5c027-89c2-4644-91fa-e48245a109c3", …
```
=> Normalize ArcGIS for SD

vaccine_feed_ingest/runners/_shared/fetch.py, vaccine_feed_ingest/runners/ma/ma_immunizations/fetch.yml, vaccine_feed_ingest/runners/ma/ma_immunizations/normalize.yml, vaccine_feed_ingest/runners/ma/ma_immunizations/parse.yml
|-|
| Resolves #241 |
| Resolves #242 |
| Resolves #243 |
State: ma |
Site: ma_immunizations |
I had to make a few tweaks to the prepmod infra to get this to work.
- Added support for extra params.  The site returns empty results if that `q[...]` param is missing, for some reason.
- Added support for headers.  The site seems to have some relatively naive bot checking.  It 403's with empty user agent, but will allow anything else in, e.g. `curl` worked just fine in my local testing.  Used the URL for this github as a fill-in, but let me know if there's a more official UA / good netizen convention for this project.
```json
{"id": "ma_immunizations:4573", "name": "Greenfield Senior Center", "address": {"street1": "35 Pleasant Street", "street2": null, "city": "Greenfield", …
```
=> Add pipeline for ma/ma_immunizations

vaccine_feed_ingest/runners/ct/state/normalize.py
|-|
| Resolves #624  |
State: CT |
Site: state |
The field "hours_of_operation" had some Nulls, so added `continue` to skip anytime a field is null
```
$ poetry run vaccine-feed-ingest all-stages ct/state
2021-05-12T15:28:42-0700 INFO:stages/ingest.py:Fetching ct/state and saving fetched output to /var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmptj2tvdd7_fetch_ct_state/output
2021-05-12T15:28:46-0700 INFO:stages/ingest.py:Copying files from /var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmptj2tvdd7_fetch_ct_state/output to out/ct/state/raw/2021-05-12T15:28:42
2021-05-12T15:28:46-0700 INFO:stages/ingest.py:Parsing ct/state and saving parsed output to /var/folders/yf/ps34_b0x5pn_ddj9skx0gwph0000gn/T/tmpurx9_unv_parse_ct_state/output
2021-05-12T15:28:46-0700 …
```
=> handle Null in fields

vaccine_feed_ingest/runners/me/maine_gov/normalize.py
|-|
| Resolves #625  |
State: ME |
Site: maine_gov |
normalize.py was creating id's in a way that did not match the regex in schema. Updated to use `location_id_from_name`.
=> use location_id_from_name to generate location_id

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/runners/us/vaccinespotter_org/normalize.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/site.py
`vaccinespotter_org` had 65KB+ record sizes because they have every appointment time available as a huge list! This was causing import to fail because the post body was too big.
We aren't using this information anywhere so I am stripping it out of the `source.data` field in the `normalize` stage. If we want to use this data in the future we can add it back as a normalized field.
I also added the ability to exclude sites when processing so I could skip the scrappers that are broken right now.
=> Impose a max source location record size of 15KB and fix vaccinespotter

vaccine_feed_ingest/runners/tx/arcgis/normalize.py
|-|
| Resolves #623  |
State: TX |
Site: arcgis |
The scraper has its own _phone_fixup method that was not handling all of the phone cases. Adding the normalize_phone util to the _get_contacts method resolved these.
=> use normalize_phone util to fix invalid phone numbers

poetry.lock, pyproject.toml, tests/stages/test_caching.py, tox.ini, vaccine_feed_ingest/stages/caching.py, vaccine_feed_ingest/stages/enrichment.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/outputs.py
Creates the concept of a cache which stores items as JSON entries in a sqllite3 DB using [diskcache](http://www.grantjenks.com/docs/diskcache).
A "api_cache" is then passed to enrichment stage and this cache can be used to cache api calls so we don't call the api everytime. Each site has its own "api_cache" so feeds can still be processed independently.
The cache is stored in GCS as a gzipped tar at each site's enrich root  (e.g. `us/vaccinespotter_org/enrich/.api_cache.tar.gz`), and is loaded at the beginning of enriching a site feed, and then stored when finished.
The usage of this cache will be defined in a future PR, but the idea is to use this like a memoize cache for api calls with a cache expire of maybe `45 +/- 15` days, so we can refresh things eventually, but not overwhelm …
=> Add caching framework for caching api calls during enrichment 

vaccine_feed_ingest/runners/il/sfsites/normalize.py
Presently the ids for `il/sf_sites` change on each run of the pipeline, so we disabled the site. Manually create a stable id instead.
=> fix: stable ids for il/sf_sites

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/caching.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/outputs.py
Added a command to remove an api cache completely, and evict keys with certain tags.
```
vaccine-feed-ingest api-cache-remove ca/sf_gov
```
```
vaccine-feed-ingest api-cache-evict ca/sf_gov --cache-tag=placekey
```
=> Commands for managing api cache

vaccine_feed_ingest/runners/wa/state/normalize.py
|-|
| Resolves #519 |
State: WA|
Site: state |
Not as thorough as I could have been, I ignored bad data instead of fixing it case by case.
I traced from a few other PRs, and I relied on the docs of the graphQL api: https://apim-vaccs-prod.azure-api.net/web/graphql
```json
{"locationId": "recT5VYLb0qwyVTSz", "locationName": "North Basin - Davenport", "locationType": null, "providerId": null, "providerName": null, "departmentId": null, "departmentName": null, "addressLine1": "100 3rd Street", "addressLine2": null, "city": "Davenport", "state": "Washington", "county": "Lincoln", "zipcode": "99122", "latitude": 47.65713, "longitude": -118.14546, "description": null, "contactFirstName": null, "contactLastName": null, "fax": null, "phone": "(509) 725-7501", "email": null, …
```
=> Normalize WA State. Fixes #519

vaccine_feed_ingest/stages/caching.py
[Pathy](https://github.com/justindujardin/pathy) uses `smart-open` to access both local and remote files via the `pathlib.Path` interface.
I was using `tarfile` to open the file which worked for local files, but not for remote files. I fixed this by switching to using Pathy to open the file before passing to tarfile, so this now uses the smart open remote/local magic.
I confirmed this worked by running it with :
```
poetry run vaccine-feed-ingest enrich ca/sf_gov --output-dir=gs://vaccine-feeds-dev/locations/
```
=> Open api-cache archive using Pathy so it works with GCS

tests/conftest.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/utils/match.py, vaccine_feed_ingest/vial.py
On 2021-05-14, `VIAL` updated its `nlgeojson` response format per feedback from a partner.
Among other updates, the `id` field which was previously available both at `.id` and `.properties.id` was consolidated to `.id` only.
Update matching logic to use the consolidated field.
NOTE: it is possible that other schema changes may be breaking to some logic herein. I did not attempt to re-validate existing matching rules against the schema changes, only to fix the issue blocking streaming locations from VIAL.
=> fix: vial `id` at root, not in properties

poetry.lock, pyproject.toml, vaccine_feed_ingest/apis/common.py, vaccine_feed_ingest/apis/placekey.py, vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/enrichment.py, vaccine_feed_ingest/stages/ingest.py
Support for adding data from external APIs during enrich stage. External API calls are cached for 35-50 days so we don't overwhelm the external service.
Placekey is free, but slow, so we may need to wait to enable this until we optimize out load-to-vial runtime
You need to get an api key from https://dev.placekey.io/ in order for this to work
e.g.
```
vaccine-feed-ingest enrich ca/sf_gov --enrich-apis=placekey --placekey-apy-key=***
```
=> Support for adding placekey concordance links from placekey.io during enrichment

tests/utils/test_normalize.py, vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/utils/normalize.py, vaccine_feed_ingest/vial.py
Calculate a content hash from the normalized location fields, and only import the source location if the hash is different.
This should greatly increase performance of loading new locations
=> Skip importing locations that haven't changed since last load

vaccine_feed_ingest/runners/sc/arcgis/normalize.py, vaccine_feed_ingest/utils/normalize.py
|-|
State: SC |
Site: arcgis |
Defensive fix for normalize bug observed in PR checks on https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/659, e.g. [here](https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/659/checks?check_run_id=2616534722#step:11:212).
=> SC: Fix error when normalizing locations

poetry.lock, pyproject.toml, vaccine_feed_ingest/apis/common.py, vaccine_feed_ingest/apis/placekey.py, vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/enrichment.py, vaccine_feed_ingest/stages/ingest.py
Reverts CAVaccineInventory/vaccine-feed-ingest#664
[`placekey` `v0.0.11`](https://github.com/Placekey/placekey-py/releases/tag/v0.0.11) fixes the issue where `placekey` adjusted the global log level to `Error`.
=> Revert "Revert "Support for adding placekey concordance links from placekey.io during enrichment""

vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/vial.py
1. Attach `content_hash` to source locations when importing
2. Retrieve `content_hash` when using the `searchSourceLocations` summary format
3. Skip loading any source location with a matching hash
=> Use round tripped content hash to skip locations that were already loaded

vaccine_feed_ingest/stages/enrichment.py
In the event the address is not set, do not attempt to use it for geocoding
=> fix: skip geocodio if there is no address at all

tests/utils/test_misc.py, vaccine_feed_ingest/stages/enrichment.py, vaccine_feed_ingest/utils/misc.py
Geocodio's python library does not handle paging api calls, and they have a maximum of 10k records per call. Process geocode requests in batches of 5k to stay well under this limit.
=> chore: page geocodio calls in batches of 5k

vaccine_feed_ingest/runners/wa/state/normalize.py
The `wa/state` data contains sites around the country. Stop over-riding the provided state in addresses, and make a few further cleanups to better support this.
- fix: use data source state value
- fix: proper source URL
- fix: accept 'PR' prefixed zips
=> fix: wa/state contains national sites

vaccine_feed_ingest/stages/enrichment.py
Geocod.io does not include the street number in the formatted_street field. Concatenate it on if it exists.
=> fix: add number to formatted street

vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/normalize.py
|-|
State: us |
Site: giscorps_vaccine_providers |
update parsing to attempt to parse addresses.
There seem to still be many addresses that are ambiguous, but this gets the majority that are fully-qualified
- [ X] I tested this using the CLI (e.g., `poetry run vaccine-feed-ingest <state>/<site>`)
- [ X] I ran auto-formatting: `poetry run tox -e lint-fix`
=> parse street addres from GISCorps dataset using usaddress library

vaccine_feed_ingest/runners/nj/vaccinate_nj/normalize.py
|-|
| Resolves #699 |
State: NJ |
Site: Vaccinate NJ |
All issues resolved
```json
{"id": "vaccinate_nj:8465a5f6-9638-4cb8-9c88-d3612e7e8ee4", "name": "Adlers Pharmacy LTC", "address": {"street1": "100 Dobbs Lane Suite 205", "city": "Cherry Hill", "state": "NJ", "zip": "08034"}, "location": {"latitude": 39.8835179, "longitude": -75.00599559999999}, "languages": ["en"], "availability": {"drop_in": false, "appointments": true}, "active": true, "source": {"source": "vaccinate_nj", "id": "8465a5f6-9638-4cb8-9c88-d3612e7e8ee4", "fetched_from_uri": "https://c19vaccinelocatornj.info/api/v1/vaccine/locations/page", "fetched_at": "2021-05-31T17:31:39.460954", "published_at": "2021-04-09T16:21:06Z", "data": {"name": "Adlers Pharmacy LTC", "id": …
```
=> Normalize Vaccinate NJ for NJ

vaccine_feed_ingest/runners/al/jefferson/normalize.py, vaccine_feed_ingest/runners/al/jefferson/parse.py
Follow-up to #697, addressing the non-blocking review suggestions by @tmb.
|-|
State: AL |
Site: Jefferson County |
Key changes:
- Refactor the `normalize` loop to hopefully make it more readable and maintainable. This is done by creating a `SiteBuilder` class that maintains state while we are processing a single entry of the parsed output, and pulling out helper functions to check or add each piece of site data.
- This code now accepts multiple phone numbers, notes, or availability entries for the same site. In practice this doesn't happen in the most recent document, so doesn't affect output.
- Filter out entries starting with "Find a location near you". In the Jefferson County PDF there is a  similar nearby entry for the same provider (healthmart), titled "Make an …
=> AL: Follow up refactoring to Jefferson County normalize step

vaccine_feed_ingest/runners/ar/state_health_units/fetch.sh
|-|
| Resolves #693  |
State: ar |
Site: state_health_units |
Straightforward fetcher script. Verified by examining the output of this command:
```sh
curl --silent https://www.healthy.arkansas.gov/local-health-units -o data.html
```
The fetched HTML has a `<table>` with _rows_ of data, where each **row** has  information about a "health unit" that administers vaccines:
```html
<tr>
<td><a href="/health-units/detail/yell-county-health-unit-dardanelle">Yell County Health Unit - Dardanelle</a></td>
<td>Dardanelle</td>
<td>479-229-3509</td>
<td>Monday, Wednesday – Friday 8am – 4:30pm and Tuesday’s 9:30am to 6pm</td>
</tr>
```
=> Fixes #693: fetch ar/state_health_units

poetry.lock, pyproject.toml, vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/ingest.py
Configure `sentry-sdk` when the `SENTRY_DSN` environment variable is set. This variable should be set to the proper endpoint for our Sentry project (e.g., `https://01231:a1232@b1233.ingest.sentry.io/1234`). This value can be pulled from [the sentry docs](https://docs.sentry.io/clients/python/) if you are logged in - be sure to click the green downward arrow in one of the examples to choose the proper project from the dropdown.
Sentry will automatically pick up on all `logger.error` messages (or actual errors) when it is enabled. Additional configuration (or sending some things to Sentry directly) is possible if desired.
=> chore: add Sentry

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/ingest.py, vaccine_feed_ingest/stages/load.py
Address PR comments from #705, and add sentry tags.
* A new environment variable, `SENTRY_ENABLE`, must be set in order for Sentry to be configured.
* Sentry errors from runners now have tags `vts.stage` (with the stage) and `vts.runner` (with the `state/site` name).
=> chore: improve sentry usage

vaccine_feed_ingest/stages/ingest.py
In #706 I set `exc_info=True` on error logs in `ingest`. This had the effect of Sentry rolling up errors from separate runners failing as the same error.
There is likely a better way to fix this, but in the meantime roll back that change and add additional text to the log message to ensure the errors are separated.
=> fix: do not include exception in log

vaccine_feed_ingest/utils/match.py
VTRCKS will assign the same id to different locations, so do not trust it for matching
=> FYI Skip VTRCKS for matching purposes

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/runners/us/getmyvax_org/normalize.py, vaccine_feed_ingest/runners/us/getmyvax_org/parse.py, vaccine_feed_ingest/stages/enrichment.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/vial.py
1. Fix naming of normalized output to be `{state}.normalized.ndjson` instead of `{state}.parsed.normalized.ndjson`
2. Add logging for more failure modes so we can see what is happening.
3. Strip out unused real-time appointment capacity. It will make the json entries smaller and faster to load.
4. Send batched of `1000` to geocodio.
5. Import batched of `100` to VIAL.
=> Miscellaneous changes to load GetMyVax

vaccine_feed_ingest/cli.py, vaccine_feed_ingest/stages/load.py, vaccine_feed_ingest/vial.py
Add an option to limit the number of records to import with `--import-limit`
This is useful for testing import without needing to match all records first.
=> Option to limit number of records to import for a site

vaccine_feed_ingest/vial.py
We continue to have timeouts. Rescue all potential exceptions and log them aggressively to attempt to debug.
=> chore: overbroad exception rescue on vial post

vaccine_feed_ingest/runners/ak/clinic_list/normalize.py
Resolves normalizer errors  in ak/clinic_list.
Issue was an assumption that the `normalize_phone` method returned a list of strings, not `Contact` objects
=> Fix akcliniclist

vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/normalize.py
|-|
| Resolves  N/A |
State: us |
Site: giscorps_vaccine_providers |
streamlines normalizing of US state names using the `us` library as suggested by @bryanculbertson in #677.
Also handles a couple additional edge cases that were causing this process to fail.
=> Update US state normalization in us/giscorps_vaccine_providers

vaccine_feed_ingest/runners/sc/dhec_arcgis/fetch.yml, vaccine_feed_ingest/runners/sc/dhec_arcgis/parse.yml
|-|
| Resolves #723 resolves #743 resolves #732 resolves #750 |
State: sc |
Site: dhec_arcgis |
simple arcgis fetch and parse using the shared runner
not sure what happened with vaccinebot and the duplicate issues tho
```json
{"attributes": {"Activated1": "Yes", "Appointments": "No", "Contact": null, "GlobalID": "b456ea0b-db46-42f4-9bbe-3df1a38e4fa8", "Loc_ID": 845, "OBJECTID": 1, "Phone_Sec": null, "Region": "Lowcountry", "SiteAddress": "137 gateway drive", "SiteAddressDetail": null, "SiteCity": "Ladson", "SitePhone": "", "SiteState": "SC", "SiteZip": "29456", "URL": null, "V_Manufacturer": null, "layer_id": 0, "loc_name": "Carolina Cataract and Vision Center", "loc_type1": "Medical practice \u2013 other specialty", "ref_ID": 954, "service_item_id": …
```
=> fetch and parse sc/dhec_arcgis

vaccine_feed_ingest/runners/sc/dab_arcgis/fetch.yml, vaccine_feed_ingest/runners/sc/dab_arcgis/parse.yml
|-|
| Resolves #726 Resolves #742 Resolves #735 Resolves #749 |
State: SC |
Site: dab_arcgis |
standard arcgis fetch and parse with shared parser
duplicate issues seem weird
```json
{"attributes": {"Appointments": "No", "Contact": null, "GlobalID": "b456ea0b-db46-42f4-9bbe-3df1a38e4fa8", "Loc_ID": 845, "OBJECTID": 1, "Phone_Sec": null, "Region": "Lowcountry", "SiteAddress": "137 gateway drive", "SiteAddressDetail": null, "SiteCity": "Ladson", "SitePhone": "", "SiteState": "SC", "SiteZip": "29456", "URL": null, "V_Manufacturer": null, "layer_id": 0, "loc_covid_id": null, "loc_name": "Carolina Cataract and Vision Center", "loc_type1": "Medical practice \u2013 other specialty", "ref_ID": 954, "service_item_id": "d5c82a2ca66440459d96d237390a852d", "vfc_text": "SCA918009", …
```
=> fetch and parse sc/dab_arcgis

vaccine_feed_ingest/runners/sc/nomad_arcgis/fetch.yml, vaccine_feed_ingest/runners/sc/nomad_arcgis/parse.yml
|-|
| Resolves #724 Resolves #745 Resolves #733  Resolves #752  |
State: sc |
Site: nomad_arcgis |
standard fetch and parse with shared parser
vaccinebot may have also messed up these issues
```json
{"attributes": {"Activated1": "Yes", "Appointments": "No", "Contact": null, "CreationDate": 1611182038000, "Creator": "watsonem", "EditDate": 1611597697000, "Editor": "OyerZDHEC", "GlobalID": "b456ea0b-db46-42f4-9bbe-3df1a38e4fa8", "Loc_ID": 845, "OBJECTID": 1, "Phone_Sec": null, "Region": "Lowcountry", "SiteAddress": "137 gateway drive", "SiteAddressDetail": null, "SiteCity": "Ladson", "SitePhone": "", "SiteState": "SC", "SiteZip": "29456", "Status": "Approved", "URL": null, "V_Manufacturer": null, "layer_id": 0, "loc_admin_city": null, "loc_admin_phone": null, …
```
=> fetch and parse sc/nomad_arcgis

vaccine_feed_ingest/runners/al/cahaba/fetch.sh
|-|
| Resolves #721  |
State: al |
Site: cahaba |
simple download of an HTML file.
vaccinebot may have messed up the issues
Data is sorta buried in the HTML
=> fetch al/cahaba

vaccine_feed_ingest/runners/us/vaccinespotter_org/normalize.py
Fixes handling of `None` values in two places: 
- handling of contacts (specifically for parsing the `url` key)
- handling of `None` in `provider_brand_name` which was causing the util function to fail.
A better fix may be to update `provider_id_from_name` in the normalizer utils to accept `None` as a value and return `None`, but this seemed like it might affect a lot more normalizers and wasn't attempted
=> Giscorps contacts provider fixes

vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/normalize.py
Resolves recent issues with the giscorps normalizer crashing due to new input and poor exception handling
=> update Giscorps error handling when parsing addresses

vaccine_feed_ingest/runners/us/giscorps_vaccine_providers/normalize.py
Go through and compare the behavior of the normalizer with the fields available from the parser to double check that every usable fields is being normalized.
Changes made:
- use the `EditDate` field as the publish date since that reflects the last time changes were made to this entry at the source
- ignore entries where `offers_vaccine` is "No"
- normalize `start_date` and `end_date` into the `opening_dates` schema entry
- fix incorrect normalization of drive through data. before it was normalizing both `No` and `Yes` to a drive through value of `True`. so yeah past me who wrote this was not very smart
=> Audit giscorps to fix incorrect data and make sure it is pulling in every field

vaccine_feed_ingest/runners/sc/dab_arcgis/normalize.py, vaccine_feed_ingest/runners/sc/dhec_arcgis/normalize.py, vaccine_feed_ingest/runners/sc/nomad_arcgis/normalize.py
|-|
| Resolves #759 Resolves #757 Resolves #756 |
State: sc |
Site: dab_arcgis shec_arcgis and nomad_arcgis |
turns out theyre all pretty much the same as the existing arcgis site. i think nomad might have a few more sites (just from looking at the number of lines in the parsed output) but i didnt want to assume there are no differences though so might as well grab them all.
All use the same normalizer except for nomad which has a slight change to include the date it was published (and of course different source names and urls)
Since the fetch stage's `.yml` supports multiple serviceItemID's all of these can easily be merged with the only block on this being some way to associate the correct source names and urls with the right data.
This could be an if-else chain based on …
=> Normalize all the arcgis sources for SC

vaccine_feed_ingest/runners/me/maine_gov/normalize.py
|-|
| related to: https://discord.com/channels/799147121357881364/808515907679682590/859617354622042123 |
State: me |
Site: maine_gov |
Fix validation so it can handle the single URL that contains a `"` and breaks the validation
=> Fix me gov validation error with urls

vaccine_feed_ingest/apis/placekey.py
As outlined in [this issue](https://github.com/Placekey/placekey-py/issues/15), the Placekey API has begun experiencing intermittent failures, which cause the python library to fail to parse the response, which present to our code as a `JSONDecodeError`.
Rescue this error and continue processing without Placekey if it occurs.
=> fix: resilient to placekey failures

vaccine_feed_ingest/runners/mn/gov/normalize.py
fix mn_gov url parsing to handle some additional typos (primarily a url with only one forward slash)
=> Mn gov url fixups

vaccine_feed_ingest/runners/us/getmyvax_org/normalize.py
getmyvax.org is removing the `eligibility` field from our location model as part of a move solidify a v1 API: https://github.com/usdigitalresponse/univaf/issues/154. That change should land later today.
I don’t think this change should really cause any issues since the field is already marked as optional. Unfortunately, I don’t have a fully working setup locally to run the tests, but this is pretty narrow.
=> getmyvax_org: Remove `eligibility` field

vaccine_feed_ingest/runners/_shared/parse.py
Just a minor change made to handle an edge case discovered in some test data while evaluating the new prepmod APIs
this does not solve any known or currently present issue, just wanted to provide the opportunity to merge a possible improvement. No hard feelings if this doesnt get merged.
=> handle missing clinic id in prepmod scrapers
